'use client';
import React, { useState, useEffect, useCallback, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import {
  Check,
  ChevronRight,
  ChevronDown,
  Zap,
  Calendar,
  DollarSign,
  Shield,
  X,
  Users,
  MessageSquare,
  User,
  Loader2,
  ArrowRight,
  Rocket,
  Phone,
  Radio,
  Database,
  Clock,
  Globe,
  Share2,
  UserCheck,
  Mail,
  Network,
  GraduationCap,
  Briefcase,
  Building2,
  Heart,
  TrendingUp,
  Trophy,
} from 'lucide-react';

// ─── Pricing ────────────────────────────────────────────────────────────────

function getPriceTier(memberCount: number): number {
  if (memberCount < 100) return 99;
  if (memberCount < 175) return 199;
  if (memberCount < 250) return 299;
  if (memberCount < 325) return 399;
  if (memberCount < 400) return 499;
  return 599;
}

// ─── Types ───────────────────────────────────────────────────────────────────

type OrgType =
  | 'Fraternity'
  | 'Sorority'
  | 'Club Sports'
  | 'Athletics'
  | 'Social Club'
  | 'Country Club'
  | 'Other';

const ORG_TYPES: OrgType[] = [
  'Fraternity',
  'Sorority',
  'Club Sports',
  'Athletics',
  'Social Club',
  'Country Club',
  'Other',
];

interface FormData {
  orgName: string;
  school: string;
  orgType: OrgType | '';
  designation: string;
  memberCount: string;
  leaderName: string;
  leaderEmail: string;
  leaderPhone: string;
  instagramHandle: string;
}

// ─── Step Indicator ──────────────────────────────────────────────────────────

const STEPS = ['Overview', 'Org Info', 'Your Launch', 'Agreement', 'Payment', 'Confirmation'];

function StepIndicator({ current }: { current: number }) {
  return (
    <div className="flex items-center justify-center gap-0 mb-10 px-4 flex-wrap gap-y-4">
      {STEPS.map((label, i) => {
        const done = i < current;
        const active = i === current;
        return (
          <React.Fragment key={label}>
            <div className="flex flex-col items-center gap-1">
              <div
                className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold transition-all
                  ${done ? 'bg-[#0F172A] text-white' : active ? 'bg-[#0F172A] text-white ring-4 ring-[#0F172A]/20' : 'bg-gray-200 text-gray-500'}`}
              >
                {done ? <Check size={14} /> : i + 1}
              </div>
              <span className={`text-xs font-medium hidden sm:block ${active ? 'text-[#0F172A]' : done ? 'text-[#0F172A]' : 'text-gray-400'}`}>
                {label}
              </span>
            </div>
            {i < STEPS.length - 1 && (
              <div className={`flex-1 h-0.5 min-w-4 max-w-16 mx-1 mt-[-12px] rounded-full transition-all ${i < current ? 'bg-[#0F172A]' : 'bg-gray-200'}`} />
            )}
          </React.Fragment>
        );
      })}
    </div>
  );
}

// ─── Full Agreement Text ─────────────────────────────────────────────────────

const FULL_AGREEMENT = `TRAILBLAIZE SOFTWARE AS A SERVICE AGREEMENT

This Software as a Service Agreement ("Agreement") is entered into between Trailblaize, Inc. ("Trailblaize") and the organization identified in this signup flow ("Client").

1. SERVICES
Trailblaize agrees to provide Client with access to the Trailblaize platform, including the alumni directory, message board, engagement tools, and related features, as further described at trailblaize.net (the "Services").

2. SUBSCRIPTION TERM
This Agreement commences on the date Client completes payment ("Effective Date") and continues for an initial term of twelve (12) months ("Initial Term"). After the Initial Term, this Agreement automatically converts to a month-to-month arrangement and may be terminated by either party with thirty (30) days written notice.

3. FEES AND PAYMENT
Client agrees to pay the monthly subscription fee determined by the member count provided at signup. Fees are billed monthly via the payment method on file with Stripe. Pricing may be updated at renewal with mutual written agreement. All fees are non-refundable except as required by law.

4. CLIENT DATA
Client retains full ownership of all data uploaded or generated by Client and its members ("Client Data"). Trailblaize will use Client Data solely to provide and improve the Services and will not sell Client Data to third parties. Client may request an export or deletion of Client Data at any time by contacting support@trailblaize.net.

5. CANCELLATION
After the Initial Term, Client may cancel this Agreement with thirty (30) days written notice to support@trailblaize.net. Cancellation does not relieve Client of the obligation to pay any fees accrued prior to the effective date of cancellation. No cancellation penalties apply after the Initial Term.

6. ACCEPTABLE USE
Client agrees to use the Services only for lawful purposes and in accordance with Trailblaize's Acceptable Use Policy. Client is responsible for all activity conducted through Client's account.

7. LIMITATION OF LIABILITY
TO THE MAXIMUM EXTENT PERMITTED BY LAW, TRAILBLAIZE'S TOTAL LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT SHALL NOT EXCEED THE FEES PAID BY CLIENT IN THE THREE (3) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM.

8. GOVERNING LAW
This Agreement shall be governed by the laws of the State of Mississippi, without regard to conflict of law principles.

9. ENTIRE AGREEMENT
This Agreement constitutes the entire agreement between the parties and supersedes all prior negotiations, representations, or agreements relating to its subject matter.

By completing the signup process and providing a typed signature, Client acknowledges that it has read, understood, and agrees to be bound by this Agreement.`;

// ─── Main Page ───────────────────────────────────────────────────────────────

function SetUpPage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const testMode = searchParams.get('test') === '1';

  const [step, setStep] = useState(0);
  const [activeChapterCount, setActiveChapterCount] = useState<number | null>(null);

  // Form state
  const [form, setForm] = useState<FormData>({
    orgName: '',
    school: '',
    orgType: '',
    designation: '',
    memberCount: '',
    leaderName: '',
    leaderEmail: '',
    leaderPhone: '',
    instagramHandle: '',
  });

  // Agreement state
  const [agreedName, setAgreedName] = useState('');
  const [agreedAuthorized, setAgreedAuthorized] = useState(false);
  const [showFullAgreement, setShowFullAgreement] = useState(false);
  const [agreedAt] = useState(() => new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }));
  const [agreedAtISO] = useState(() => new Date().toISOString());

  // Payment state
  const [checkoutLoading, setCheckoutLoading] = useState(false);
  const [checkoutError, setCheckoutError] = useState('');
  const [discountCode, setDiscountCode] = useState('');

  // Confirmation state
  const [confirmLoading, setConfirmLoading] = useState(false);
  const [confirmError, setConfirmError] = useState('');
  const [confirmDone, setConfirmDone] = useState(false);

  // Validation
  const [errors, setErrors] = useState<Partial<Record<keyof FormData, string>>>({});

  const price = form.memberCount ? getPriceTier(Number(form.memberCount)) : null;

  // Handle URL params on load
  useEffect(() => {
    const success = searchParams.get('success');
    const sessionId = searchParams.get('session_id');
    const stepParam = searchParams.get('step');

    const bypassParam = searchParams.get('bypass');
    if (success === 'true' && bypassParam === '1') {
      // Internal bypass — extract all params from URL
      setStep(5);
      const bypassData: Record<string, string> = {};
      searchParams.forEach((v, k) => { bypassData[k] = v; });
      handleBypassConfirmation(bypassData);
    } else if (success === 'true' && sessionId) {
      setStep(5);
      handleConfirmation(sessionId);
    } else if (stepParam) {
      setStep(Number(stepParam));
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Fetch active chapter count
  useEffect(() => {
    fetch('/api/chapters?status=active')
      .then((r) => r.json())
      .then((data) => {
        const chapters = data?.data || [];
        const active = Array.isArray(chapters)
          ? chapters.filter((c: { status: string }) => c.status === 'active').length
          : 0;
        setActiveChapterCount(active);
      })
      .catch(() => setActiveChapterCount(null));
  }, []);

  const handleBypassConfirmation = useCallback(async (params: Record<string, string>) => {
    setConfirmLoading(true); setConfirmError('');
    try {
      const res = await fetch('/api/set-up/complete', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ bypass: true, ...params }),
      });
      const data = await res.json();
      if (!res.ok || data.error) setConfirmError(data.error || 'Something went wrong.');
      else setConfirmDone(true);
    } catch { setConfirmError('Network error. Please contact support@trailblaize.net.'); }
    finally { setConfirmLoading(false); }
  }, []);

  const handleConfirmation = useCallback(async (sessionId: string) => {
    setConfirmLoading(true);
    setConfirmError('');
    try {
      const res = await fetch('/api/set-up/complete', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ sessionId }),
      });
      const data = await res.json();
      if (!res.ok || data.error) {
        setConfirmError(data.error || 'Something went wrong. Please contact support@trailblaize.net.');
      } else {
        setConfirmDone(true);
      }
    } catch {
      setConfirmError('Network error. Please contact support@trailblaize.net.');
    } finally {
      setConfirmLoading(false);
    }
  }, []);

  function updateForm(field: keyof FormData, value: string) {
    setForm((prev) => ({ ...prev, [field]: value }));
    setErrors((prev) => ({ ...prev, [field]: '' }));
  }

  function validateStep1(): boolean {
    const newErrors: Partial<Record<keyof FormData, string>> = {};
    if (!form.orgName.trim()) newErrors.orgName = 'Organization name is required';
    if (!form.school.trim()) newErrors.school = 'School / institution is required';
    if (!form.orgType) newErrors.orgType = 'Please select an org type';
    if (!form.memberCount || Number(form.memberCount) < 1) newErrors.memberCount = 'Member count is required';
    if (!form.leaderName.trim()) newErrors.leaderName = 'Leader name is required';
    if (!form.leaderEmail.trim()) newErrors.leaderEmail = 'Email is required';
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.leaderEmail)) newErrors.leaderEmail = 'Invalid email';
    if (!form.leaderPhone.trim()) newErrors.leaderPhone = 'Phone is required';
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }

  function goToStep(n: number) {
    setStep(n);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  async function handleCheckout() {
    setCheckoutLoading(true);
    setCheckoutError('');
    try {
      const res = await fetch('/api/set-up/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...form,
          memberCount: Number(form.memberCount),
          agreedName,
          agreedAt: agreedAtISO,
          // Promo codes handled natively by Stripe checkout
        }),
      });
      const data = await res.json();
      if (!res.ok || data.error) {
        setCheckoutError(data.error || 'Failed to create checkout session.');
      } else if (data.url) {
        window.location.href = data.url;
      }
    } catch {
      setCheckoutError('Network error. Please try again.');
    } finally {
      setCheckoutLoading(false);
    }
  }

  // ─── Step 0: Value Page ────────────────────────────────────────────────────

  if (step === 0) {
    return (
      <div style={{ background: 'white', minHeight: '100vh', fontFamily: 'Inter, system-ui, sans-serif' }}>
        <style>{`
          @keyframes fadeUp {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
          }
          @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
          }
          @keyframes nodeDrift {
            0%, 100% { transform: translate(0px, 0px); }
            33% { transform: translate(3px, -4px); }
            66% { transform: translate(-3px, 2px); }
          }
          @keyframes lineAppear {
            from { stroke-dashoffset: 300; opacity: 0; }
            to { stroke-dashoffset: 0; opacity: 1; }
          }
          @keyframes dotPop {
            from { transform: scale(0); opacity: 0; }
            to { transform: scale(1); opacity: 1; }
          }
          @keyframes iconSlideIn {
            from { opacity: 0; transform: translateY(12px); }
            to { opacity: 1; transform: translateY(0); }
          }
          .org-types-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 16px;
          }
          @media (max-width: 640px) {
            .org-types-grid {
              grid-template-columns: repeat(2, 1fr);
            }
          }
        `}</style>

        {testMode && (
          <div style={{ background: '#fef3c7', borderBottom: '1px solid #f59e0b', padding: '8px 16px', textAlign: 'center', fontSize: '0.8125rem', fontWeight: 600, color: '#92400e' }}>
            🧪 TEST MODE — No real charges will be made
          </div>
        )}

        {/* Nav — matches trailblaize.net */}
        <nav style={{ padding: '0 32px', height: '64px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid #F3F4F6', background: 'white' }}>
          <img src="/logos/logo-wordmark-navy.png" alt="Trailblaize" style={{ height: '44px' }} />
          <button onClick={() => goToStep(1)}
            style={{ padding: '8px 20px', borderRadius: '8px', background: '#0F172A', color: 'white', fontWeight: 600, fontSize: '0.875rem', border: 'none', cursor: 'pointer', fontFamily: 'inherit' }}>
            Get Started
          </button>
        </nav>

        {/* ── Hero ── */}
        <section style={{ maxWidth: '680px', margin: '0 auto', padding: '88px 24px 72px', textAlign: 'center' }}>
          <div style={{ animation: 'fadeUp 0.6s ease both' }}>
            <h1 style={{
              fontSize: 'clamp(2.5rem, 6vw, 4rem)',
              fontWeight: 400,
              lineHeight: 1.08,
              color: '#0F172A',
              marginBottom: '20px',
              fontFamily: '"Instrument Serif", Georgia, serif',
              letterSpacing: '-0.02em',
            }}>
              The alumni network for every organization.
            </h1>
            <p style={{ fontSize: '1.125rem', color: '#6B7280', lineHeight: 1.65, maxWidth: '460px', margin: '0 auto 40px' }}>
              A shared social network where organizations own their alumni community.
            </p>
            <button
              onClick={() => goToStep(1)}
              style={{
                padding: '13px 32px', borderRadius: '8px',
                background: '#0F172A', color: 'white',
                fontWeight: 600, fontSize: '1rem',
                border: 'none', cursor: 'pointer',
                fontFamily: 'inherit',
                display: 'inline-flex', alignItems: 'center', gap: '8px',
              }}
            >
              Get Started <ArrowRight size={16} />
            </button>
          </div>
        </section>

        {/* ── Section 1: One Place for Everyone (#F9FAFB) ── */}
        <section style={{ background: '#F9FAFB', borderTop: '1px solid #E5E7EB', borderBottom: '1px solid #E5E7EB', padding: '72px 24px' }}>
          <div style={{ maxWidth: '860px', margin: '0 auto' }}>
            <div style={{ textAlign: 'center', marginBottom: '48px', animation: 'fadeUp 0.6s ease 0.1s both' }}>
              <div style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '44px', height: '44px', borderRadius: '12px', background: 'white', border: '1px solid #E5E7EB', marginBottom: '16px' }}>
                <Users size={20} color="#10B981" />
              </div>
              <h2 style={{ fontSize: '1.75rem', fontWeight: 700, color: '#111827', margin: '0 0 12px', letterSpacing: '-0.01em' }}>
                One place for everyone
              </h2>
              <p style={{ fontSize: '1rem', color: '#6B7280', lineHeight: 1.65, maxWidth: '440px', margin: '0 auto' }}>
                Your members, alumni, and leadership - connected in a single private network your organization actually owns.
              </p>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '16px' }}>
              {[
                { icon: <Users size={18} color="#10B981" />, title: 'Private member directory', desc: 'Every member, past and present, in one searchable space.', delay: '0.15s' },
                { icon: <MessageSquare size={18} color="#10B981" />, title: 'Instant messaging', desc: 'Message anyone in your org directly - no group chats scattered across apps.', delay: '0.25s' },
                { icon: <Shield size={18} color="#10B981" />, title: 'You control access', desc: 'Approve who joins, manage roles, keep your network clean.', delay: '0.35s' },
              ].map((card) => (
                <div
                  key={card.title}
                  style={{
                    background: 'white',
                    border: '1px solid #E5E7EB',
                    borderRadius: '14px',
                    padding: '24px',
                    animation: `iconSlideIn 0.5s ease ${card.delay} both`,
                  }}
                >
                  <div style={{ marginBottom: '12px' }}>{card.icon}</div>
                  <h3 style={{ fontSize: '0.9375rem', fontWeight: 600, color: '#111827', margin: '0 0 8px' }}>{card.title}</h3>
                  <p style={{ fontSize: '0.875rem', color: '#6B7280', margin: 0, lineHeight: 1.6 }}>{card.desc}</p>
                </div>
              ))}
            </div>
            {/* Product screenshots */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '24px', marginTop: '48px' }}>
              <div style={{ borderRadius: '12px', border: '1px solid #E5E7EB', overflow: 'hidden', background: '#F9FAFB', display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '200px' }}>
                <img
                  src="/setup-screenshots/feed.png"
                  alt="Social feed"
                  style={{ width: '100%', display: 'block', borderRadius: '12px' }}
                  onError={(e) => {
                    (e.target as HTMLImageElement).style.display = 'none';
                    const p = document.createElement('p');
                    p.textContent = 'Feed Preview';
                    p.style.cssText = 'color:#9CA3AF;font-weight:500;margin:0;font-family:Inter,sans-serif;';
                    (e.target as HTMLImageElement).parentElement!.appendChild(p);
                  }}
                />
              </div>
              <div style={{ borderRadius: '12px', border: '1px solid #E5E7EB', overflow: 'hidden', background: '#F9FAFB', display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '200px' }}>
                <img
                  src="/setup-screenshots/alumni.png"
                  alt="Alumni directory"
                  style={{ width: '100%', display: 'block', borderRadius: '12px' }}
                  onError={(e) => {
                    (e.target as HTMLImageElement).style.display = 'none';
                    const p = document.createElement('p');
                    p.textContent = 'Alumni Directory';
                    p.style.cssText = 'color:#9CA3AF;font-weight:500;margin:0;font-family:Inter,sans-serif;';
                    (e.target as HTMLImageElement).parentElement!.appendChild(p);
                  }}
                />
              </div>
            </div>
          </div>
        </section>

        {/* ── Section 2: Real Connections (white) ── */}
        <section style={{ background: 'white', padding: '80px 24px' }}>
          <div style={{ maxWidth: '860px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '64px', alignItems: 'center' }}>
            <div style={{ animation: 'fadeUp 0.6s ease 0.1s both' }}>
              <div style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '64px', height: '64px', borderRadius: '12px', background: '#F0FDF4', border: '1px solid #D1FAE5', marginBottom: '20px' }}>
                <Share2 size={32} color="#10B981" />
              </div>
              <h2 style={{ fontSize: '1.625rem', fontWeight: 700, color: '#111827', margin: '0 0 14px', letterSpacing: '-0.01em' }}>
                Real connections, not just contacts
              </h2>
              <p style={{ fontSize: '0.9375rem', color: '#6B7280', lineHeight: 1.7, margin: '0 0 12px' }}>
                Members find jobs, mentors, and friendships through your alumni network - matched by industry, city, and shared interests.
              </p>
              <p style={{ fontSize: '0.9375rem', color: '#6B7280', lineHeight: 1.7, margin: 0 }}>
                Whether you're a new grad looking for your first role or an alum giving back - Trailblaize makes the introduction.
              </p>
            </div>
            {/* Alumni directory screenshot */}
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
              <img
                src="/setup-screenshots/alumni.png"
                alt="Alumni directory with profiles"
                style={{ width: '100%', maxWidth: '360px', borderRadius: '12px', border: '1px solid #E5E7EB', display: 'block' }}
                onError={(e) => {
                  const el = e.target as HTMLImageElement;
                  el.style.display = 'none';
                  const wrap = el.parentElement!;
                  wrap.style.cssText += 'min-height:200px;background:#F9FAFB;border-radius:12px;border:1px solid #E5E7EB;align-items:center;justify-content:center;';
                  const p = document.createElement('p');
                  p.textContent = 'Alumni Directory';
                  p.style.cssText = 'color:#9CA3AF;font-weight:500;margin:0;font-family:Inter,sans-serif;';
                  wrap.appendChild(p);
                }}
              />
            </div>
          </div>
        </section>

        {/* ── Section 3: Built for Your Organization (#F9FAFB) ── */}
        <section style={{ background: '#F9FAFB', borderTop: '1px solid #E5E7EB', borderBottom: '1px solid #E5E7EB', padding: '72px 24px' }}>
          <div style={{ maxWidth: '860px', margin: '0 auto', textAlign: 'center' }}>
            <div style={{ marginBottom: '48px', animation: 'fadeUp 0.6s ease 0.1s both' }}>
              <div style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '44px', height: '44px', borderRadius: '12px', background: 'white', border: '1px solid #E5E7EB', marginBottom: '16px' }}>
                <Zap size={20} color="#10B981" />
              </div>
              <h2 style={{ fontSize: '1.75rem', fontWeight: 700, color: '#111827', margin: '0 0 12px', letterSpacing: '-0.01em' }}>
                Built for your organization
              </h2>
              <p style={{ fontSize: '1rem', color: '#6B7280', lineHeight: 1.65, maxWidth: '440px', margin: '0 auto' }}>
                Whether you&apos;re a university, Greek chapter, high school, or professional network - Trailblaize works for you.
              </p>
            </div>
            <div className="org-types-grid">
              {[
                { icon: <GraduationCap size={18} color="#10B981" />, label: 'Universities / Business Schools', d: '0.15s' },
                { icon: <Users size={18} color="#10B981" />, label: 'Greek Life Chapters', d: '0.2s' },
                { icon: <Globe size={18} color="#10B981" />, label: 'High Schools', d: '0.25s' },
                { icon: <Briefcase size={18} color="#10B981" />, label: 'Professional Associations', d: '0.3s' },
                { icon: <Building2 size={18} color="#10B981" />, label: 'Corporate Alumni Networks', d: '0.35s' },
                { icon: <Heart size={18} color="#10B981" />, label: 'Philanthropic / Advisory Boards', d: '0.4s' },
                { icon: <TrendingUp size={18} color="#10B981" />, label: 'Investor / Founder Networks', d: '0.45s' },
                { icon: <Trophy size={18} color="#10B981" />, label: 'Athletic Programs / Teams', d: '0.5s' },
              ].map((item) => (
                <div
                  key={item.label}
                  style={{
                    background: 'white',
                    border: '1px solid #E5E7EB',
                    borderRadius: '12px',
                    padding: '20px 16px',
                    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px',
                    animation: `iconSlideIn 0.5s ease ${item.d} both`,
                  }}
                >
                  {item.icon}
                  <span style={{ fontSize: '0.8125rem', fontWeight: 600, color: '#374151' }}>{item.label}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── CTA ── */}
        <section style={{ background: 'white', padding: '80px 24px', textAlign: 'center' }}>
          <div style={{ maxWidth: '480px', margin: '0 auto', animation: 'fadeUp 0.6s ease 0.1s both' }}>
            <h2 style={{ fontSize: '1.75rem', fontWeight: 700, color: '#111827', margin: '0 0 12px', letterSpacing: '-0.01em' }}>
              Ready to activate your network?
            </h2>
            <p style={{ fontSize: '0.9375rem', color: '#6B7280', margin: '0 0 32px', lineHeight: 1.65 }}>
              Takes about 5 minutes to set up.
            </p>
            <button
              onClick={() => goToStep(1)}
              style={{
                padding: '14px 36px', borderRadius: '8px',
                background: '#10B981', color: 'white',
                fontWeight: 600, fontSize: '1rem',
                border: 'none', cursor: 'pointer',
                fontFamily: 'inherit',
                display: 'inline-flex', alignItems: 'center', gap: '8px',
              }}
            >
              Get Started <ArrowRight size={16} />
            </button>
          </div>
        </section>
      </div>
    );
  }

  // ─── Step 1: Org Info ─────────────────────────────────────────────────────

  if (step === 1) {
    return (
      <PageShell testMode={testMode}>
        <StepIndicator current={1} />
        <Card>
          <h2 style={S.h2}>Tell us about your organization</h2>
          <p style={S.sub}>We&apos;ll use this to set up your account.</p>

          <div style={S.fieldWrap}>
            <Field label="Organization Name *" error={errors.orgName}>
              <input
                type="text"
                value={form.orgName}
                onChange={(e) => updateForm('orgName', e.target.value)}
                placeholder="e.g. Sigma Chi, Campus Cycling Club"
                style={S.input(!!errors.orgName)}
              />
            </Field>

            <Field label="School / Institution *" error={errors.school}>
              <input
                type="text"
                value={form.school}
                onChange={(e) => updateForm('school', e.target.value)}
                placeholder="e.g. University of Alabama"
                style={S.input(!!errors.school)}
              />
            </Field>

            <Field label="Org Type *" error={errors.orgType}>
              <div className="flex flex-wrap gap-2">
                {ORG_TYPES.map((type) => (
                  <button
                    key={type}
                    type="button"
                    onClick={() => updateForm('orgType', type)}
                    className={`px-4 py-2 rounded-xl text-sm font-medium border transition-all
                      ${form.orgType === type
                        ? 'bg-[#0F172A] text-white border-[#0F172A]'
                        : 'bg-white text-gray-600 border-gray-200 hover:border-[#0F172A]/40'}`}
                  >
                    {type}
                  </button>
                ))}
              </div>
            </Field>

            <Field label="Chapter / Team Designation" hint="e.g. Alpha Beta, Varsity, etc.">
              <input
                type="text"
                value={form.designation}
                onChange={(e) => updateForm('designation', e.target.value)}
                placeholder="Optional"
                style={S.input(false)}
              />
            </Field>

            <Field label="Total Member Count *" hint="Active + alumni combined — approximate is fine" error={errors.memberCount}>
              <input
                type="number"
                min={1}
                value={form.memberCount}
                onChange={(e) => updateForm('memberCount', e.target.value)}
                placeholder="e.g. 250"
                style={S.input(!!errors.memberCount)}
              />
            </Field>

            {/* Pricing shown on payment page, not here */}

            <Field label="Leader Name *" hint="President / Captain / Director" error={errors.leaderName}>
              <input
                type="text"
                value={form.leaderName}
                onChange={(e) => updateForm('leaderName', e.target.value)}
                placeholder="Full name"
                style={S.input(!!errors.leaderName)}
              />
            </Field>

            <Field label="Leader Email *" error={errors.leaderEmail}>
              <input
                type="email"
                value={form.leaderEmail}
                onChange={(e) => updateForm('leaderEmail', e.target.value)}
                placeholder="you@email.com"
                style={S.input(!!errors.leaderEmail)}
              />
            </Field>

            <Field label="Leader Phone *" error={errors.leaderPhone}>
              <input
                type="tel"
                value={form.leaderPhone}
                onChange={(e) => updateForm('leaderPhone', e.target.value)}
                placeholder="+1 (555) 000-0000"
                style={S.input(!!errors.leaderPhone)}
              />
            </Field>

            <Field label="Instagram Handle" hint="Optional">
              <div className="flex items-center">
                <span className="px-3 py-2.5 bg-gray-100 text-gray-500 rounded-l-lg border border-gray-200 border-r-0 text-sm">@</span>
                <input
                  type="text"
                  value={form.instagramHandle}
                  onChange={(e) => updateForm('instagramHandle', e.target.value.replace('@', ''))}
                  placeholder="yourchapter"
                  className="flex-1 px-3 py-2.5 border border-gray-200 rounded-r-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#0F172A]/20 focus:border-[#0F172A]"
                />
              </div>
            </Field>
          </div>

          <div style={S.actions}>
            <button
              onClick={() => goToStep(0)}
              style={S.backBtn}
            >
              ← Back
            </button>
            <NavButton
              onClick={() => {
                if (validateStep1()) goToStep(2);
              }}
            >
              Continue <ChevronRight size={16} />
            </NavButton>
          </div>
        </Card>
      </PageShell>
    );
  }

  // ─── Step 2: Member Activation — Roll Out ────────────────────────

  if (step === 2) {
    return (
      <div style={{ fontFamily: 'Inter, system-ui, sans-serif', minHeight: '100vh', background: 'white' }}>
        <style>{`
          @keyframes nodePulse {
            0%, 100% { transform: scale(1); opacity: 0.85; }
            50% { transform: scale(1.3); opacity: 1; }
          }
          @keyframes fadeUp {
            from { opacity: 0; transform: translateY(24px); }
            to { opacity: 1; transform: translateY(0); }
          }
          @keyframes checkPop {
            0% { transform: scale(0) rotate(-10deg); opacity: 0; }
            65% { transform: scale(1.18) rotate(3deg); opacity: 1; }
            100% { transform: scale(1) rotate(0); opacity: 1; }
          }
          @keyframes floatY {
            0%, 100% { transform: translateY(0px); }
            50% { transform: translateY(-7px); }
          }
          @keyframes lineGrow {
            from { stroke-dashoffset: 200; opacity: 0; }
            to { stroke-dashoffset: 0; opacity: 1; }
          }
          @keyframes orbitIn {
            from { transform: scale(0); opacity: 0; }
            to { transform: scale(1); opacity: 1; }
          }
          @keyframes glowPulse {
            0%, 100% { box-shadow: 0 0 0 0 rgba(16,185,129,0.4); }
            50% { box-shadow: 0 0 0 10px rgba(16,185,129,0); }
          }
          @keyframes rowFade {
            0% { opacity: 0.3; transform: translateX(-8px); }
            100% { opacity: 1; transform: translateX(0); }
          }
          @keyframes hubPulse {
            0%, 100% { transform: scale(1); }
            50% { transform: scale(1.08); }
          }
        `}</style>

        {testMode && (
          <div style={{ background: '#fef3c7', borderBottom: '1px solid #f59e0b', padding: '8px 16px', textAlign: 'center', fontSize: '0.8125rem', fontWeight: 600, color: '#92400e' }}>
            🧪 TEST MODE — No real charges will be made
          </div>
        )}

        <nav style={{ background: 'white', borderBottom: '1px solid #F3F4F6', padding: '12px 24px', display: 'flex', alignItems: 'center' }}>
          <img src="/logos/logo-wordmark-navy.png" alt="Trailblaize" style={{ height: '28px' }} />
        </nav>

        <div style={{ background: 'white' }}>
          <div style={{ maxWidth: '640px', margin: '0 auto', padding: '24px 24px 0' }}>
            <StepIndicator current={2} />
          </div>
        </div>

        {/* Hero */}
        <section style={{ background: '#0F172A', padding: '64px 24px 52px', textAlign: 'center' }}>
          <div style={{ maxWidth: '580px', margin: '0 auto', animation: 'fadeUp 0.7s ease both' }}>
            <span style={{ display: 'inline-block', background: 'rgba(16,185,129,0.14)', color: '#10B981', borderRadius: '100px', padding: '4px 14px', fontSize: '0.72rem', fontWeight: 700, letterSpacing: '0.09em', textTransform: 'uppercase', marginBottom: '20px' }}>
              Your Onboarding Plan
            </span>
            <h2 style={{ fontSize: 'clamp(1.875rem, 5vw, 2.75rem)', fontWeight: 400, color: 'white', margin: '0 0 16px', lineHeight: 1.15, fontFamily: '"Instrument Serif", Georgia, serif', letterSpacing: '-0.01em' }}>
              Here’s how we launch your alumni network.
            </h2>
            <p style={{ fontSize: '1rem', color: 'rgba(255,255,255,0.6)', lineHeight: 1.7, margin: 0 }}>
              From day one, our team works alongside yours — every single step of the way.
            </p>
          </div>
        </section>

        {/* Section 1: Collaborative Launch — dark */}
        <section style={{ background: '#0F172A', padding: '56px 24px 72px', borderTop: '1px solid rgba(255,255,255,0.06)' }}>
          <div style={{ maxWidth: '860px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '48px', alignItems: 'center' }}>
            <div style={{ animation: 'fadeUp 0.7s ease 0.1s both' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '14px' }}>
                <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: 'rgba(16,185,129,0.13)', display: 'flex', alignItems: 'center', justifyContent: 'center', animation: 'glowPulse 2.8s ease infinite' }}>
                  <Rocket size={20} color="#10B981" />
                </div>
                <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#10B981', textTransform: 'uppercase', letterSpacing: '0.09em' }}>Step 1</span>
              </div>
              <h3 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'white', margin: '0 0 12px', lineHeight: 1.2 }}>Collaborative Launch</h3>
              <p style={{ fontSize: '0.9375rem', color: 'rgba(255,255,255,0.6)', lineHeight: 1.7, margin: '0 0 10px' }}>
                We create a <strong style={{ color: 'rgba(255,255,255,0.85)' }}>collaborative Instagram post with your chapter</strong> — driving early adopters to join from day one.
              </p>
              <p style={{ fontSize: '0.9375rem', color: 'rgba(255,255,255,0.6)', lineHeight: 1.7, margin: 0 }}>
                Those early adopters become your ambassadors, bringing in the rest of your alumni through real word-of-mouth. The network effect starts here.
              </p>
            </div>
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
              <svg viewBox="0 0 260 160" width="260" height="160" style={{ overflow: 'visible' }}>
                {[
                  [0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[0,3],[1,4]
                ].map(([a,b], i) => {
                  const pts = [{x:48,y:30},{x:130,y:20},{x:212,y:40},{x:220,y:120},{x:130,y:140},{x:40,y:120}];
                  return <line key={i} x1={pts[a].x} y1={pts[a].y} x2={pts[b].x} y2={pts[b].y}
                    stroke="rgba(16,185,129,0.25)" strokeWidth="1.5"
                    strokeDasharray="200" strokeDashoffset="200"
                    style={{ animation: `lineGrow 0.6s ease ${i * 0.2 + 0.2}s both` }} />;
                })}
                {[
                  {cx:48,cy:30},{cx:130,cy:20},{cx:212,cy:40},{cx:220,cy:120},{cx:130,cy:140},{cx:40,cy:120}
                ].map((n,i) => (
                  <circle key={i} cx={n.cx} cy={n.cy} r="9" fill="#10B981"
                    style={{ animation: `orbitIn 0.4s ease ${i * 0.15}s both, nodePulse 2.4s ease ${i * 0.4}s infinite` }}
                  />
                ))}
              </svg>
            </div>
          </div>
        </section>

        {/* Section 2: Activate Your Network — white */}
        <section style={{ background: 'white', padding: '72px 24px' }}>
          <div style={{ maxWidth: '860px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '48px', alignItems: 'center' }}>
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', order: 0 }}>
              <svg viewBox="0 0 260 160" width="260" height="160" style={{ overflow: 'visible' }}>
                <circle cx="130" cy="80" r="22" fill="#0F172A" style={{ animation: 'hubPulse 2.5s ease infinite' }} />
                <text x="130" y="85" textAnchor="middle" fill="white" fontSize="11" fontWeight="700">YOU</text>
                {[
                  {cx:42,cy:32,label:'JD',d:'0.2s'},{cx:218,cy:32,label:'MK',d:'0.4s'},
                  {cx:218,cy:128,label:'TR',d:'0.6s'},{cx:42,cy:128,label:'SL',d:'0.8s'},
                  {cx:130,cy:14,label:'AB',d:'1.0s'},
                ].map((p,i) => (
                  <g key={i} style={{ animation: `orbitIn 0.5s ease ${p.d} both` }}>
                    <line x1={p.cx} y1={p.cy} x2="130" y2="80" stroke="#E5E7EB" strokeWidth="1.5"
                      strokeDasharray="200" strokeDashoffset="200"
                      style={{ animation: `lineGrow 0.5s ease ${p.d} both` }} />
                    <circle cx={p.cx} cy={p.cy} r="16" fill="#F3F4F6" stroke="#E5E7EB" strokeWidth="1.5" />
                    <text x={p.cx} y={p.cy+4} textAnchor="middle" fill="#374151" fontSize="9" fontWeight="600">{p.label}</text>
                  </g>
                ))}
              </svg>
            </div>
            <div style={{ order: 1, animation: 'fadeUp 0.7s ease 0.2s both' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '14px' }}>
                <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: '#f0fdf4', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <Phone size={20} color="#0F172A" />
                </div>
                <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#10B981', textTransform: 'uppercase', letterSpacing: '0.09em' }}>Step 2</span>
              </div>
              <h3 style={{ fontSize: '1.4rem', fontWeight: 700, color: '#0F172A', margin: '0 0 12px', lineHeight: 1.2 }}>Activate Your Network</h3>
              <p style={{ fontSize: '0.9375rem', color: '#6B7280', lineHeight: 1.7, margin: '0 0 10px' }}>
                We personally call your early adopters — connecting them with each other by industry, city, and shared interests.
              </p>
              <p style={{ fontSize: '0.9375rem', color: '#6B7280', lineHeight: 1.7, margin: 0 }}>
                Looking for a job, a mentor, advice, or just curious who’s really in your network? We make those introductions happen.
              </p>
            </div>
          </div>
        </section>

        {/* Section 3: Meet Alumni Where They Are — dark */}
        <section style={{ background: '#0F172A', padding: '72px 24px' }}>
          <div style={{ maxWidth: '860px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '48px', alignItems: 'center' }}>
            <div style={{ animation: 'fadeUp 0.7s ease 0.1s both' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '14px' }}>
                <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: 'rgba(16,185,129,0.13)', display: 'flex', alignItems: 'center', justifyContent: 'center', animation: 'glowPulse 2.8s ease 0.4s infinite' }}>
                  <Radio size={20} color="#10B981" />
                </div>
                <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#10B981', textTransform: 'uppercase', letterSpacing: '0.09em' }}>Step 3</span>
              </div>
              <h3 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'white', margin: '0 0 12px', lineHeight: 1.2 }}>Meet Alumni Where They Are</h3>
              <p style={{ fontSize: '0.9375rem', color: 'rgba(255,255,255,0.6)', lineHeight: 1.7, margin: '0 0 10px' }}>
                We utilize any channels you already have — Facebook groups, LinkedIn, GroupMe — providing <strong style={{ color: 'rgba(255,255,255,0.85)' }}>custom flyers, blurbs, and a private sign-up link</strong> for each.
              </p>
              <p style={{ fontSize: '0.9375rem', color: 'rgba(255,255,255,0.6)', lineHeight: 1.7, margin: 0 }}>
                Alumni can also find your space on our mobile app and request access. You approve or reject — you’re always in control.
              </p>
            </div>
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
              <div style={{ position: 'relative', width: '220px', height: '160px' }}>
                <div style={{ position: 'absolute', left: '50%', top: '50%', transform: 'translate(-50%,-50%)', width: '52px', height: '52px', borderRadius: '14px', background: '#10B981', display: 'flex', alignItems: 'center', justifyContent: 'center', animation: 'hubPulse 2.5s ease infinite', zIndex: 2 }}>
                  <Share2 size={22} color="white" />
                </div>
                {[
                  {label:'f', bg:'#1877F2', top:'4px', left:'10px', d:'0.2s'},
                  {label:'in', bg:'#0A66C2', top:'4px', right:'10px', d:'0.4s'},
                  {label:'G', bg:'#25D366', bottom:'4px', left:'10px', d:'0.6s'},
                  {label:'✉', bg:'#6366F1', bottom:'4px', right:'10px', d:'0.8s'},
                  {label:'📱', bg:'#374151', top:'calc(50% - 20px)', right:'-2px', d:'1.0s'},
                ].map((c,i) => (
                  <div key={i} style={{
                    position: 'absolute',
                    ...(c.top !== undefined ? {top: c.top} : {}),
                    ...(c.bottom !== undefined ? {bottom: c.bottom} : {}),
                    ...(c.left !== undefined ? {left: c.left} : {}),
                    ...(c.right !== undefined ? {right: c.right} : {}),
                    width: '40px', height: '40px', borderRadius: '10px', background: c.bg,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    color: 'white', fontSize: '0.75rem', fontWeight: 700,
                    animation: `orbitIn 0.5s ease ${c.d} both, floatY 3s ease ${i * 0.5}s infinite`,
                    zIndex: 1,
                  }}>
                    {c.label}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Section 4: Database Outreach — white */}
        <section style={{ background: 'white', padding: '72px 24px' }}>
          <div style={{ maxWidth: '860px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '48px', alignItems: 'center' }}>
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', order: 0 }}>
              <div style={{ width: '240px', background: '#F9FAFB', border: '1px solid #E5E7EB', borderRadius: '12px', overflow: 'hidden', animation: 'fadeUp 0.7s ease both' }}>
                <div style={{ background: '#0F172A', padding: '8px 14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Database size={14} color="#10B981" />
                  <span style={{ color: 'white', fontSize: '0.75rem', fontWeight: 600 }}>alumni_contacts.csv</span>
                </div>
                {[
                  {name:'James D.', d:'0.2s'},{name:'Maria K.', d:'0.5s'},
                  {name:'Tyler R.', d:'0.8s'},{name:'Sara L.', d:'1.1s'},{name:'Alex B.', d:'1.4s'},
                ].map((row,i) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '9px 14px', borderBottom: '1px solid #F3F4F6', animation: `rowFade 0.5s ease ${row.d} both` }}>
                    <span style={{ fontSize: '0.8125rem', fontWeight: 600, color: '#111827' }}>{row.name}</span>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                      <Mail size={12} color="#10B981" style={{ animation: `checkPop 0.4s ease ${parseFloat(row.d) + 0.3}s both`, opacity: 0 }} />
                      <div style={{ width: '16px', height: '16px', borderRadius: '50%', background: '#f0fdf4', display: 'flex', alignItems: 'center', justifyContent: 'center', animation: `checkPop 0.4s ease ${parseFloat(row.d) + 0.5}s both`, opacity: 0 }}>
                        <Check size={9} color="#16a34a" strokeWidth={3} />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div style={{ order: 1, animation: 'fadeUp 0.7s ease 0.2s both' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '14px' }}>
                <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: '#f0fdf4', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <Database size={20} color="#0F172A" />
                </div>
                <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#10B981', textTransform: 'uppercase', letterSpacing: '0.09em' }}>Step 4</span>
              </div>
              <h3 style={{ fontSize: '1.4rem', fontWeight: 700, color: '#0F172A', margin: '0 0 12px', lineHeight: 1.2 }}>Database Outreach</h3>
              <p style={{ fontSize: '0.9375rem', color: '#6B7280', lineHeight: 1.7, margin: '0 0 10px' }}>
                Have a spreadsheet of alumni contacts? We <strong style={{ color: '#111827' }}>email every alumni three times</strong> and personally text everyone via iMessage.
              </p>
              <p style={{ fontSize: '0.9375rem', color: '#6B7280', lineHeight: 1.7, margin: 0 }}>
                We verify contact info, clean up the data, and invite each one personally to join your platform.
              </p>
            </div>
          </div>
        </section>

        {/* Section 5: Alumni Sign Up in Minutes — dark */}
        <section style={{ background: '#0F172A', padding: '72px 24px' }}>
          <div style={{ maxWidth: '860px', margin: '0 auto' }}>
            <div style={{ marginBottom: '36px', animation: 'fadeUp 0.7s ease both' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '14px' }}>
                <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: 'rgba(16,185,129,0.13)', display: 'flex', alignItems: 'center', justifyContent: 'center', animation: 'glowPulse 2.8s ease 0.6s infinite' }}>
                  <Clock size={20} color="#10B981" />
                </div>
                <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#10B981', textTransform: 'uppercase', letterSpacing: '0.09em' }}>Step 5</span>
              </div>
              <h3 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'white', margin: '0 0 10px', lineHeight: 1.2 }}>Alumni Sign Up in Minutes</h3>
              <p style={{ fontSize: '0.9375rem', color: 'rgba(255,255,255,0.6)', lineHeight: 1.7, margin: 0, maxWidth: '480px' }}>
                Once alumni receive the invite, joining is frictionless. Create a profile, join your space, done. Then the whole network opens up.
              </p>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px' }}>
              {[
                {icon:<User size={22} color="#10B981" />, title:'Create Profile', desc:'Name, photo, industry, city, graduation year', d:'0.2s'},
                {icon:<Users size={22} color="#10B981" />, title:'Join Your Space', desc:'Request access — admin approves in one tap', d:'0.5s'},
                {icon:<Check size={22} color="#10B981" />, title:'Fully Connected', desc:'Text & email alumni, store org info, accept donations', d:'0.8s'},
              ].map((s,i) => (
                <div key={i} style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '14px', padding: '24px 20px', animation: `fadeUp 0.6s ease ${s.d} both` }}>
                  <div style={{ width: '44px', height: '44px', borderRadius: '12px', background: 'rgba(16,185,129,0.12)', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '14px', animation: `checkPop 0.5s ease ${parseFloat(s.d) + 0.3}s both` }}>
                    {s.icon}
                  </div>
                  <h4 style={{ fontSize: '1rem', fontWeight: 700, color: 'white', margin: '0 0 6px' }}>{s.title}</h4>
                  <p style={{ fontSize: '0.8125rem', color: 'rgba(255,255,255,0.55)', lineHeight: 1.6, margin: 0 }}>{s.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Section 6: Your Digital Community — white */}
        <section style={{ background: 'white', padding: '72px 24px' }}>
          <div style={{ maxWidth: '860px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '48px', alignItems: 'center' }}>
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', order: 0 }}>
              <svg viewBox="0 0 260 180" width="260" height="180" style={{ overflow: 'visible' }}>
                <circle cx="130" cy="90" r="18" fill="#0F172A" style={{ animation: 'hubPulse 2.5s ease infinite' }} />
                <text x="130" y="94" textAnchor="middle" fill="white" fontSize="9" fontWeight="700">TB</text>
                {[
                  {cx:86,cy:52,d:'0.2s'},{cx:174,cy:52,d:'0.4s'},
                  {cx:174,cy:128,d:'0.6s'},{cx:86,cy:128,d:'0.8s'},
                ].map((n,i) => (
                  <g key={i}>
                    <line x1="130" y1="90" x2={n.cx} y2={n.cy} stroke="#E5E7EB" strokeWidth="1.5"
                      strokeDasharray="200" strokeDashoffset="200"
                      style={{ animation: `lineGrow 0.5s ease ${n.d} both` }} />
                    <circle cx={n.cx} cy={n.cy} r="11" fill="#10B981"
                      style={{ animation: `orbitIn 0.4s ease ${n.d} both, nodePulse 2.6s ease ${i * 0.5}s infinite` }} />
                  </g>
                ))}
                {[
                  {cx:42,cy:38,fromX:86,fromY:52,d:'1.0s'},{cx:218,cy:38,fromX:174,fromY:52,d:'1.2s'},
                  {cx:218,cy:142,fromX:174,fromY:128,d:'1.4s'},{cx:42,cy:142,fromX:86,fromY:128,d:'1.6s'},
                  {cx:130,cy:12,fromX:130,fromY:90,d:'1.8s'},{cx:130,cy:168,fromX:130,fromY:90,d:'2.0s'},
                ].map((n,i) => (
                  <g key={i}>
                    <line x1={n.fromX} y1={n.fromY} x2={n.cx} y2={n.cy} stroke="#F3F4F6" strokeWidth="1"
                      strokeDasharray="200" strokeDashoffset="200"
                      style={{ animation: `lineGrow 0.4s ease ${n.d} both` }} />
                    <circle cx={n.cx} cy={n.cy} r="7" fill="#F3F4F6" stroke="#E5E7EB" strokeWidth="1.5"
                      style={{ animation: `orbitIn 0.4s ease ${n.d} both` }} />
                  </g>
                ))}
              </svg>
            </div>
            <div style={{ order: 1, animation: 'fadeUp 0.7s ease 0.2s both' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '14px' }}>
                <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: '#f0fdf4', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <Globe size={20} color="#0F172A" />
                </div>
                <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#10B981', textTransform: 'uppercase', letterSpacing: '0.09em' }}>Step 6</span>
              </div>
              <h3 style={{ fontSize: '1.4rem', fontWeight: 700, color: '#0F172A', margin: '0 0 12px', lineHeight: 1.2 }}>Your Digital Community</h3>
              <p style={{ fontSize: '0.9375rem', color: '#6B7280', lineHeight: 1.7, margin: '0 0 10px' }}>
                The digital space and community you’ve built for your entire organization. Network effect and word of mouth take over.
              </p>
              <p style={{ fontSize: '0.9375rem', color: '#6B7280', lineHeight: 1.7, margin: 0 }}>
                Trailblaize becomes the <strong style={{ color: '#111827' }}>living, breathing alumni network</strong> your organization has always needed.
              </p>
            </div>
          </div>
        </section>

        {/* CTA */}
        <section style={{ background: '#0F172A', padding: '56px 24px' }}>
          <div style={{ maxWidth: '560px', margin: '0 auto', textAlign: 'center', animation: 'fadeUp 0.7s ease both' }}>
            <h3 style={{ fontSize: '1.5rem', fontWeight: 400, color: 'white', margin: '0 0 10px', fontFamily: '"Instrument Serif", Georgia, serif' }}>
              Ready to build your network?
            </h3>
            <p style={{ fontSize: '0.9375rem', color: 'rgba(255,255,255,0.5)', margin: '0 0 32px', lineHeight: 1.6 }}>
              Sign the agreement and you’re minutes away from a live alumni platform.
            </p>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <button onClick={() => goToStep(1)} style={{ ...S.backBtn, color: 'rgba(255,255,255,0.4)' }}>
                ← Back
              </button>
              <NavButton onClick={() => goToStep(3)}>
                Continue to Agreement <ChevronRight size={16} />
              </NavButton>
            </div>
          </div>
        </section>
      </div>
    );
  }

  // ─── Step 3: Agreement ────────────────────────────────────────────────────

  if (step === 3) {
    const canProceed = agreedName.trim().length > 0 && agreedAuthorized;

    return (
      <PageShell testMode={testMode}>
        <StepIndicator current={3} />
        <Card>
          <h2 style={S.h2}>Here&apos;s what you&apos;re agreeing to</h2>
          <p style={S.sub}>Plain language, no surprises.</p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', marginBottom: '28px' }}>
            {[
              { icon: <Zap size={18} color="#0F172A" />, title: "What you're getting", desc: "Access to the full Trailblaize platform — alumni directory, message board, engagement tools, and ongoing support." },
              { icon: <Calendar size={18} color="#0F172A" />, title: 'Your commitment', desc: "12-month commitment starting today. After year one, cancel anytime with 30 days notice. No hidden fees." },
              { icon: <DollarSign size={18} color="#0F172A" />, title: 'What it costs', desc: price ? `$${price}/month · Billed monthly · Based on ${form.memberCount} members. Pricing reviewed at renewal.` : 'Pricing based on your member count.' },
              { icon: <Shield size={18} color="#0F172A" />, title: 'Your data', desc: "Your data belongs to you. We use it only to run the platform. Never sold. Export or delete anytime." },
              { icon: <X size={18} color="#6B7280" />, title: 'Cancellation', desc: "Cancel after year one with 30 days written notice. Outstanding fees due at cancellation." },
            ].map((card) => (
              <div key={card.title} style={{ background: 'white', border: '1px solid #E5E7EB', borderRadius: '12px', padding: '16px 20px', display: 'flex', gap: '14px', alignItems: 'flex-start' }}>
                <div style={{ flexShrink: 0, marginTop: '1px' }}>{card.icon}</div>
                <div>
                  <p style={{ fontSize: '0.875rem', fontWeight: 600, color: '#111827', margin: '0 0 4px 0' }}>{card.title}</p>
                  <p style={{ fontSize: '0.8125rem', color: '#6B7280', lineHeight: 1.5, margin: 0 }}>{card.desc}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Full agreement toggle */}
          <button type="button" onClick={() => setShowFullAgreement(v => !v)}
            style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.8125rem', fontWeight: 600, color: '#0F172A', background: 'none', border: 'none', cursor: 'pointer', marginBottom: '12px', fontFamily: 'inherit' }}>
            {showFullAgreement ? 'Hide full agreement ↑' : 'Read full agreement ↓'}
          </button>

          {showFullAgreement && (
            <div style={{ background: '#F9FAFB', border: '1px solid #E5E7EB', borderRadius: '12px', padding: '16px', marginBottom: '20px', maxHeight: '240px', overflowY: 'auto' }}>
              <pre style={{ fontSize: '0.6875rem', color: '#6B7280', whiteSpace: 'pre-wrap', fontFamily: 'inherit', lineHeight: 1.6, margin: 0 }}>{FULL_AGREEMENT}</pre>
            </div>
          )}

          {/* Signature section */}
          <div style={{ background: '#F9FAFB', border: '1px solid #E5E7EB', borderRadius: '14px', padding: '20px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <p style={{ fontSize: '0.875rem', color: '#374151', fontWeight: 500, margin: 0 }}>
              I agree to these terms on behalf of <span style={{ color: '#111827', fontWeight: 700 }}>{form.orgName || 'my organization'}</span>
            </p>
            <div>
              <label style={S.label}>Type your full name to sign *</label>
              <input type="text" value={agreedName} onChange={e => setAgreedName(e.target.value)}
                placeholder="Your full name"
                style={{ ...S.input(false), fontFamily: 'cursive, Georgia, serif', fontSize: '1rem', color: '#111827' }} />
            </div>
            <div>
              <label style={S.label}>Date</label>
              <p style={{ ...S.input(false), display: 'block', color: '#6B7280', lineHeight: '1.5', padding: '10px 12px' }}>{agreedAt}</p>
            </div>
            <label style={{ display: 'flex', alignItems: 'flex-start', gap: '12px', cursor: 'pointer' }}>
              <div onClick={() => setAgreedAuthorized(v => !v)}
                style={{ width: '20px', height: '20px', borderRadius: '4px', border: `2px solid ${agreedAuthorized ? '#0F172A' : '#D1D5DB'}`, background: agreedAuthorized ? '#0F172A' : 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: '1px', cursor: 'pointer' }}>
                {agreedAuthorized && <Check size={12} color="white" />}
              </div>
              <span style={{ fontSize: '0.875rem', color: '#374151', lineHeight: 1.5 }}>I confirm I am authorized to enter into this agreement on behalf of my organization</span>
            </label>
          </div>

          <div style={S.actions}>
            <button
              onClick={() => goToStep(2)}
              style={S.backBtn}
            >
              ← Back
            </button>
            <NavButton
              onClick={() => { if (canProceed) goToStep(4); }}
              disabled={!canProceed}
            >
              Continue to Payment <ChevronRight size={16} />
            </NavButton>
          </div>
        </Card>
      </PageShell>
    );
  }

  // ─── Step 4: Payment ──────────────────────────────────────────────────────

  if (step === 4) {
    return (
      <PageShell testMode={testMode}>
        <StepIndicator current={4} />
        <Card>
          <h2 style={S.h2}>Complete your payment</h2>
          <p style={S.sub}>You&apos;ll be redirected to Stripe&apos;s secure checkout.</p>

          {/* Summary */}
          <div className="bg-gray-50 border border-gray-200 rounded-2xl p-6 mb-6 space-y-3">
            <h3 className="font-semibold text-[#0F172A] mb-3">Order Summary</h3>
            <Row label="Organization" value={form.orgName} />
            <Row label="School" value={form.school} />
            <Row label="Type" value={form.orgType} />
            <Row label="Members" value={`${form.memberCount} members`} />
            <div className="border-t border-gray-200 pt-3 mt-3">
              <Row
                label="Monthly Price"
                value={price ? `$${price}/month` : '—'}
                valueClass="text-[#0F172A] font-bold text-lg"
              />
            </div>
            <p className="text-xs text-gray-400 pt-1">Annual commitment, then month-to-month · Cancel after year one with 30 days notice</p>
          </div>

          <div className="flex items-center gap-2 text-sm text-gray-500 mb-6">
            <Shield size={16} className="text-gray-400" />
            <span>Secured by Stripe — your payment info is never stored on our servers</span>
          </div>

          {checkoutError && (
            <div style={{ background: '#fef2f2', color: '#dc2626', borderRadius: '10px', padding: '12px 16px', fontSize: '0.875rem', marginBottom: '16px' }}>
              {checkoutError}
            </div>
          )}

          <div style={S.actions}>
            <button
              onClick={() => goToStep(3)}
              style={S.backBtn}
            >
              ← Back
            </button>
            <NavButton onClick={handleCheckout} disabled={checkoutLoading}>
              {checkoutLoading ? (
                <><Loader2 size={16} className="animate-spin" /> Redirecting...</>
              ) : (
                <>Complete Payment <ArrowRight size={16} /></>
              )}
            </NavButton>
          </div>
        </Card>
      </PageShell>
    );
  }

  // ─── Step 5: Confirmation ─────────────────────────────────────────────────

  return (
    <PageShell testMode={testMode}>
      <StepIndicator current={5} />
      <Card>
        {confirmLoading ? (
          <div style={{ padding: '64px 0', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '16px', textAlign: 'center' }}>
            <Loader2 size={36} style={{ animation: 'spin 1s linear infinite', color: '#0F172A' }} />
            <p style={{ color: '#6B7280', fontSize: '0.875rem', margin: 0 }}>Setting up your account…</p>
          </div>
        ) : confirmError ? (
          <div style={{ padding: '48px 0', textAlign: 'center' }}>
            <p style={{ color: '#dc2626', fontWeight: 600, marginBottom: '8px', fontSize: '0.9375rem' }}>Something went wrong</p>
            <p style={{ color: '#6B7280', fontSize: '0.875rem', marginBottom: '20px' }}>{confirmError}</p>
            <a href="mailto:support@trailblaize.net" style={{ color: '#0F172A', fontSize: '0.875rem', fontWeight: 600 }}>Contact support</a>
          </div>
        ) : (
          <>
            {/* Checkmark */}
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', marginBottom: '28px' }}>
              <div style={{ width: '72px', height: '72px', borderRadius: '50%', background: '#f0fdf4', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '16px', border: '1px solid #bbf7d0' }}>
                <Check size={36} color="#16a34a" strokeWidth={2.5} />
              </div>
              <h2 style={{ fontSize: '1.75rem', fontWeight: 700, color: '#111827', margin: '0 0 6px 0' }}>You&apos;re in.</h2>
              {(form.orgName || form.school) && (
                <p style={{ color: '#6B7280', fontSize: '0.875rem', margin: 0 }}>{form.orgName}{form.school ? ` · ${form.school}` : ''}</p>
              )}
            </div>

            {/* What happens next */}
            <div style={{ background: '#F9FAFB', border: '1px solid #E5E7EB', borderRadius: '14px', padding: '20px', marginBottom: '24px' }}>
              <p style={{ fontSize: '0.8125rem', fontWeight: 700, color: '#374151', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '0 0 16px 0' }}>What happens next</p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                {[
                  { emoji: '✅', text: 'Your account is being created' },
                  { emoji: '📱', text: "We'll reach out within 24 hours to help with your launch post" },
                  { emoji: '📅', text: 'Book your onboarding call to get set up for success' },
                  { emoji: '🔑', text: 'Log in and start activating your alumni network' },
                ].map(item => (
                  <div key={item.text} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px' }}>
                    <span style={{ fontSize: '1rem', flexShrink: 0 }}>{item.emoji}</span>
                    <span style={{ fontSize: '0.875rem', color: '#374151', lineHeight: 1.5 }}>{item.text}</span>
                  </div>
                ))}
              </div>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              <a href="https://calendly.com/owen-trailblaize/30min" target="_blank" rel="noopener noreferrer"
                style={{ display: 'block', textAlign: 'center', padding: '12px 24px', borderRadius: '10px', border: '1.5px solid #0F172A', color: '#0F172A', fontWeight: 600, fontSize: '0.875rem', textDecoration: 'none', fontFamily: 'Inter, system-ui, sans-serif' }}>
                Book Onboarding Call
              </a>
              <a href="https://www.trailblaize.net/sign-in"
                style={{ display: 'block', textAlign: 'center', padding: '12px 24px', borderRadius: '10px', background: '#0F172A', color: 'white', fontWeight: 600, fontSize: '0.875rem', textDecoration: 'none', fontFamily: 'Inter, system-ui, sans-serif' }}>
                Log In →
              </a>
            </div>
          </>
        )}
      </Card>
    </PageShell>
  );
}

// ─── Helper Components ───────────────────────────────────────────────────────

function PageShell({ children, testMode }: { children: React.ReactNode; testMode?: boolean }) {
  return (
    <div style={{ background: '#F9FAFB', minHeight: '100vh' }}>
      {testMode && (
        <div style={{ background: '#fef3c7', borderBottom: '1px solid #f59e0b', padding: '8px 16px', textAlign: 'center', fontSize: '0.8125rem', fontWeight: 600, color: '#92400e' }}>
          🧪 TEST MODE — Use card 4242 4242 4242 4242 · No real charges will be made
        </div>
      )}
      <nav style={{ background: 'white', borderBottom: '1px solid #F3F4F6', padding: '12px 24px', display: 'flex', alignItems: 'center' }}>
        <img src="/logos/logo-wordmark-navy.png" alt="Trailblaize" style={{ height: '28px' }} />
      </nav>
      <main style={{ maxWidth: '640px', margin: '0 auto', padding: '32px 24px 64px' }}>
        {children}
      </main>
    </div>
  );
}

const S = {
  card: { background: 'white', border: '1px solid #E5E7EB', borderRadius: '16px', padding: '28px' },
  h2: { fontSize: '1.375rem', fontWeight: 700, color: '#111827', margin: '0 0 6px 0', fontFamily: 'Inter, system-ui, sans-serif' },
  sub: { fontSize: '0.875rem', color: '#6B7280', margin: '0 0 28px 0' },
  fieldWrap: { display: 'flex', flexDirection: 'column' as const, gap: '20px' },
  label: { display: 'block', fontSize: '0.8125rem', fontWeight: 600, color: '#374151', marginBottom: '6px', fontFamily: 'Inter, system-ui, sans-serif' },
  hint: { fontSize: '0.75rem', color: '#9ca3af', marginTop: '4px' },
  error: { fontSize: '0.75rem', color: '#ef4444', marginTop: '4px' },
  input: (hasError: boolean) => ({
    width: '100%', padding: '10px 12px', fontSize: '0.875rem',
    border: `1px solid ${hasError ? '#ef4444' : '#E5E7EB'}`,
    borderRadius: '10px', outline: 'none', fontFamily: 'Inter, system-ui, sans-serif',
    boxSizing: 'border-box' as const, color: '#111827', background: 'white',
  }),
  row: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '0.875rem' } as const,
  actions: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '28px' },
  backBtn: { fontSize: '0.875rem', color: '#9ca3af', background: 'none', border: 'none', cursor: 'pointer', fontFamily: 'Inter, system-ui, sans-serif', display: 'flex', alignItems: 'center', gap: '4px' },
  primaryBtn: (disabled?: boolean) => ({
    display: 'inline-flex', alignItems: 'center', gap: '6px',
    padding: '10px 24px', borderRadius: '10px',
    background: disabled ? '#D1D5DB' : '#0F172A',
    color: 'white', fontWeight: 600, fontSize: '0.875rem',
    border: 'none', cursor: disabled ? 'not-allowed' : 'pointer',
    fontFamily: 'Inter, system-ui, sans-serif',
  }),
};

function Card({ children }: { children: React.ReactNode }) {
  return <div style={S.card}>{children}</div>;
}

function Field({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: React.ReactNode }) {
  return (
    <div>
      <label style={S.label}>{label}</label>
      {children}
      {hint && !error && <p style={S.hint}>{hint}</p>}
      {error && <p style={S.error}>{error}</p>}
    </div>
  );
}

function Row({ label, value, valueClass }: { label: string; value: string; valueClass?: string }) {
  return (
    <div style={S.row}>
      <span style={{ color: '#6B7280' }}>{label}</span>
      <span style={valueClass === 'font-bold text-emerald-600' ? { fontWeight: 700, color: '#10b981' } : { fontWeight: 600, color: '#111827' }}>{value}</span>
    </div>
  );
}

function NavButton({ onClick, disabled, children }: { onClick: () => void; disabled?: boolean; children: React.ReactNode }) {
  return (
    <button type="button" onClick={onClick} disabled={disabled} style={S.primaryBtn(disabled)}>
      {children}
    </button>
  );
}

function inputCls(_hasError: boolean) {
  // Legacy — kept for any remaining uses; new code uses S.input()
  return '';
}

// Wrap in Suspense so useSearchParams() works with Next.js static export
export default function SetUpPageWrapper() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-[#F9FAFB] flex items-center justify-center"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#0F172A]" /></div>}>
      <SetUpPage />
    </Suspense>
  );
}
