'use client';

import React, { useState, useEffect, useCallback, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import {
  Check,
  ChevronRight,
  ChevronDown,
  Zap,
  Calendar,
  DollarSign,
  Shield,
  X,
  Users,
  MessageSquare,
  User,
  Loader2,
  ArrowRight,
} from 'lucide-react';

// ─── Pricing ────────────────────────────────────────────────────────────────

function getPriceTier(memberCount: number): number {
  if (memberCount < 100) return 99;
  if (memberCount < 175) return 199;
  if (memberCount < 250) return 299;
  if (memberCount < 325) return 399;
  if (memberCount < 400) return 499;
  return 599;
}

// ─── Types ───────────────────────────────────────────────────────────────────

type OrgType =
  | 'Fraternity'
  | 'Sorority'
  | 'Club Sports'
  | 'Athletics'
  | 'Social Club'
  | 'Country Club'
  | 'Other';

const ORG_TYPES: OrgType[] = [
  'Fraternity',
  'Sorority',
  'Club Sports',
  'Athletics',
  'Social Club',
  'Country Club',
  'Other',
];

interface FormData {
  orgName: string;
  school: string;
  orgType: OrgType | '';
  designation: string;
  memberCount: string;
  leaderName: string;
  leaderEmail: string;
  leaderPhone: string;
  instagramHandle: string;
}

// ─── Step Indicator ──────────────────────────────────────────────────────────

const STEPS = ['Overview', 'Org Info', 'Agreement', 'Payment', 'Confirmation'];

function StepIndicator({ current }: { current: number }) {
  return (
    <div className="flex items-center justify-center gap-0 mb-10 px-4 flex-wrap gap-y-4">
      {STEPS.map((label, i) => {
        const done = i < current;
        const active = i === current;
        return (
          <React.Fragment key={label}>
            <div className="flex flex-col items-center gap-1">
              <div
                className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold transition-all
                  ${done ? 'bg-[#0F172A] text-white' : active ? 'bg-[#0F172A] text-white ring-4 ring-[#0F172A]/20' : 'bg-gray-200 text-gray-500'}`}
              >
                {done ? <Check size={14} /> : i + 1}
              </div>
              <span className={`text-xs font-medium hidden sm:block ${active ? 'text-[#0F172A]' : done ? 'text-[#0F172A]' : 'text-gray-400'}`}>
                {label}
              </span>
            </div>
            {i < STEPS.length - 1 && (
              <div className={`flex-1 h-0.5 min-w-4 max-w-16 mx-1 mt-[-12px] rounded-full transition-all ${i < current ? 'bg-[#0F172A]' : 'bg-gray-200'}`} />
            )}
          </React.Fragment>
        );
      })}
    </div>
  );
}

// ─── Full Agreement Text ─────────────────────────────────────────────────────

const FULL_AGREEMENT = `TRAILBLAIZE SOFTWARE AS A SERVICE AGREEMENT

This Software as a Service Agreement ("Agreement") is entered into between Trailblaize, Inc. ("Trailblaize") and the organization identified in this signup flow ("Client").

1. SERVICES
Trailblaize agrees to provide Client with access to the Trailblaize platform, including the alumni directory, message board, engagement tools, and related features, as further described at trailblaize.net (the "Services").

2. SUBSCRIPTION TERM
This Agreement commences on the date Client completes payment ("Effective Date") and continues for an initial term of twelve (12) months ("Initial Term"). After the Initial Term, this Agreement automatically converts to a month-to-month arrangement and may be terminated by either party with thirty (30) days written notice.

3. FEES AND PAYMENT
Client agrees to pay the monthly subscription fee determined by the member count provided at signup. Fees are billed monthly via the payment method on file with Stripe. Pricing may be updated at renewal with mutual written agreement. All fees are non-refundable except as required by law.

4. CLIENT DATA
Client retains full ownership of all data uploaded or generated by Client and its members ("Client Data"). Trailblaize will use Client Data solely to provide and improve the Services and will not sell Client Data to third parties. Client may request an export or deletion of Client Data at any time by contacting support@trailblaize.net.

5. CANCELLATION
After the Initial Term, Client may cancel this Agreement with thirty (30) days written notice to support@trailblaize.net. Cancellation does not relieve Client of the obligation to pay any fees accrued prior to the effective date of cancellation. No cancellation penalties apply after the Initial Term.

6. ACCEPTABLE USE
Client agrees to use the Services only for lawful purposes and in accordance with Trailblaize's Acceptable Use Policy. Client is responsible for all activity conducted through Client's account.

7. LIMITATION OF LIABILITY
TO THE MAXIMUM EXTENT PERMITTED BY LAW, TRAILBLAIZE'S TOTAL LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT SHALL NOT EXCEED THE FEES PAID BY CLIENT IN THE THREE (3) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM.

8. GOVERNING LAW
This Agreement shall be governed by the laws of the State of Mississippi, without regard to conflict of law principles.

9. ENTIRE AGREEMENT
This Agreement constitutes the entire agreement between the parties and supersedes all prior negotiations, representations, or agreements relating to its subject matter.

By completing the signup process and providing a typed signature, Client acknowledges that it has read, understood, and agrees to be bound by this Agreement.`;

// ─── Main Page ───────────────────────────────────────────────────────────────

function SetUpPage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const testMode = searchParams.get('test') === '1';

  const [step, setStep] = useState(0);
  const [activeChapterCount, setActiveChapterCount] = useState<number | null>(null);

  // Form state
  const [form, setForm] = useState<FormData>({
    orgName: '',
    school: '',
    orgType: '',
    designation: '',
    memberCount: '',
    leaderName: '',
    leaderEmail: '',
    leaderPhone: '',
    instagramHandle: '',
  });

  // Agreement state
  const [agreedName, setAgreedName] = useState('');
  const [agreedAuthorized, setAgreedAuthorized] = useState(false);
  const [showFullAgreement, setShowFullAgreement] = useState(false);
  const [agreedAt] = useState(() => new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }));
  const [agreedAtISO] = useState(() => new Date().toISOString());

  // Payment state
  const [checkoutLoading, setCheckoutLoading] = useState(false);
  const [checkoutError, setCheckoutError] = useState('');

  // Confirmation state
  const [confirmLoading, setConfirmLoading] = useState(false);
  const [confirmError, setConfirmError] = useState('');
  const [confirmDone, setConfirmDone] = useState(false);

  // Validation
  const [errors, setErrors] = useState<Partial<Record<keyof FormData, string>>>({});

  const price = form.memberCount ? getPriceTier(Number(form.memberCount)) : null;

  // Handle URL params on load
  useEffect(() => {
    const success = searchParams.get('success');
    const sessionId = searchParams.get('session_id');
    const stepParam = searchParams.get('step');

    if (success === 'true' && sessionId) {
      setStep(4);
      handleConfirmation(sessionId);
    } else if (stepParam) {
      setStep(Number(stepParam));
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Fetch active chapter count
  useEffect(() => {
    fetch('/api/chapters?status=active')
      .then((r) => r.json())
      .then((data) => {
        const chapters = data?.data || [];
        const active = Array.isArray(chapters)
          ? chapters.filter((c: { status: string }) => c.status === 'active').length
          : 0;
        setActiveChapterCount(active);
      })
      .catch(() => setActiveChapterCount(null));
  }, []);

  const handleConfirmation = useCallback(async (sessionId: string) => {
    setConfirmLoading(true);
    setConfirmError('');
    try {
      const res = await fetch('/api/set-up/complete', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ sessionId }),
      });
      const data = await res.json();
      if (!res.ok || data.error) {
        setConfirmError(data.error || 'Something went wrong. Please contact support@trailblaize.net.');
      } else {
        setConfirmDone(true);
      }
    } catch {
      setConfirmError('Network error. Please contact support@trailblaize.net.');
    } finally {
      setConfirmLoading(false);
    }
  }, []);

  function updateForm(field: keyof FormData, value: string) {
    setForm((prev) => ({ ...prev, [field]: value }));
    setErrors((prev) => ({ ...prev, [field]: '' }));
  }

  function validateStep1(): boolean {
    const newErrors: Partial<Record<keyof FormData, string>> = {};
    if (!form.orgName.trim()) newErrors.orgName = 'Organization name is required';
    if (!form.school.trim()) newErrors.school = 'School / institution is required';
    if (!form.orgType) newErrors.orgType = 'Please select an org type';
    if (!form.memberCount || Number(form.memberCount) < 1) newErrors.memberCount = 'Member count is required';
    if (!form.leaderName.trim()) newErrors.leaderName = 'Leader name is required';
    if (!form.leaderEmail.trim()) newErrors.leaderEmail = 'Email is required';
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.leaderEmail)) newErrors.leaderEmail = 'Invalid email';
    if (!form.leaderPhone.trim()) newErrors.leaderPhone = 'Phone is required';
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }

  function goToStep(n: number) {
    setStep(n);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  async function handleCheckout() {
    setCheckoutLoading(true);
    setCheckoutError('');
    try {
      const res = await fetch('/api/set-up/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...form,
          memberCount: Number(form.memberCount),
          agreedName,
          agreedAt: agreedAtISO,
          testMode,
        }),
      });
      const data = await res.json();
      if (!res.ok || data.error) {
        setCheckoutError(data.error || 'Failed to create checkout session.');
      } else if (data.url) {
        window.location.href = data.url;
      }
    } catch {
      setCheckoutError('Network error. Please try again.');
    } finally {
      setCheckoutLoading(false);
    }
  }

  // ─── Step 0: Value Page ────────────────────────────────────────────────────

  if (step === 0) {
    return (
      <div style={{ background: '#F9FAFB', minHeight: '100vh', fontFamily: 'Inter, system-ui, sans-serif' }}>
        {testMode && (
          <div style={{ background: '#fef3c7', borderBottom: '1px solid #f59e0b', padding: '8px 16px', textAlign: 'center', fontSize: '0.8125rem', fontWeight: 600, color: '#92400e' }}>
            🧪 TEST MODE — No real charges will be made
          </div>
        )}
        {/* Nav */}
        <nav style={{ background: 'white', borderBottom: '1px solid #E5E7EB', padding: '0 24px', height: '56px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <img src="/logos/logo-wordmark-navy.png" alt="Trailblaize" style={{ height: '28px' }} />
          <button
            onClick={() => goToStep(1)}
            style={{ fontSize: '0.875rem', fontWeight: 600, color: '#0F172A', background: 'none', border: 'none', cursor: 'pointer', fontFamily: 'inherit' }}
          >
            Get started →
          </button>
        </nav>

        {/* Hero */}
        <section style={{ maxWidth: '720px', margin: '0 auto', padding: '64px 24px 48px', textAlign: 'center' }}>
          <h1 style={{ fontSize: 'clamp(2rem, 5vw, 3.25rem)', fontWeight: 700, lineHeight: 1.15, color: '#111827', marginBottom: '16px', fontFamily: 'Inter, system-ui, sans-serif' }}>
            Activate your alumni network.
          </h1>
          <p style={{ fontSize: '1.125rem', color: '#6B7280', marginBottom: '32px', lineHeight: 1.6 }}>
            The platform that keeps your organization connected long after graduation.
          </p>
          <button
            onClick={() => goToStep(1)}
            style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '12px 28px', borderRadius: '10px', background: '#0F172A', color: 'white', fontWeight: 600, fontSize: '1rem', border: 'none', cursor: 'pointer', fontFamily: 'inherit' }}
          >
            Get Started <ArrowRight size={18} />
          </button>
          {activeChapterCount !== null && activeChapterCount > 0 && (
            <p style={{ marginTop: '16px', fontSize: '0.875rem', color: '#9ca3af' }}>
              Join <span style={{ fontWeight: 600, color: '#111827' }}>{activeChapterCount} organizations</span> already on Trailblaize
            </p>
          )}
        </section>

        {/* Feature Cards */}
        <section style={{ maxWidth: '900px', margin: '0 auto', padding: '0 24px 64px' }}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '16px' }}>
            {[
              {
                icon: <Users size={22} color="#0F172A" />,
                title: 'Alumni Pipeline',
                desc: 'See every alumni, their industry, location, and how to reach them.',
              },
              {
                icon: <MessageSquare size={22} color="#0F172A" />,
                title: 'Message Board',
                desc: 'Post announcements, opportunities, and updates your alumni actually see.',
              },
              {
                icon: <User size={22} color="#0F172A" />,
                title: 'Alumni Profiles',
                desc: 'Every member gets a profile card with chapter, graduation year, industry, and location.',
              },
            ].map((card) => (
              <div
                key={card.title}
                style={{ background: 'white', border: '1px solid #E5E7EB', borderRadius: '14px', padding: '20px' }}
              >
                <div style={{ marginBottom: '10px' }}>{card.icon}</div>
                <h3 style={{ fontWeight: 700, color: '#111827', fontSize: '0.9375rem', marginBottom: '6px', margin: '0 0 6px 0' }}>{card.title}</h3>
                <p style={{ color: '#6B7280', fontSize: '0.875rem', lineHeight: 1.5, margin: 0 }}>{card.desc}</p>
              </div>
            ))}
          </div>
          <div style={{ marginTop: '32px', textAlign: 'center' }}>
            <p style={{ fontSize: '0.875rem', color: '#9ca3af' }}>Plans start at <span style={{ fontWeight: 600, color: '#111827' }}>$99/month</span> based on your member count.</p>
          </div>
        </section>
      </div>
    );
  }

  // ─── Step 1: Org Info ─────────────────────────────────────────────────────

  if (step === 1) {
    return (
      <PageShell testMode={testMode}>
        <StepIndicator current={1} />
        <Card>
          <h2 style={S.h2}>Tell us about your organization</h2>
          <p style={S.sub}>We&apos;ll use this to set up your account.</p>

          <div style={S.fieldWrap}>
            <Field label="Organization Name *" error={errors.orgName}>
              <input
                type="text"
                value={form.orgName}
                onChange={(e) => updateForm('orgName', e.target.value)}
                placeholder="e.g. Sigma Chi, Campus Cycling Club"
                style={S.input(!!errors.orgName)}
              />
            </Field>

            <Field label="School / Institution *" error={errors.school}>
              <input
                type="text"
                value={form.school}
                onChange={(e) => updateForm('school', e.target.value)}
                placeholder="e.g. University of Alabama"
                style={S.input(!!errors.school)}
              />
            </Field>

            <Field label="Org Type *" error={errors.orgType}>
              <div className="flex flex-wrap gap-2">
                {ORG_TYPES.map((type) => (
                  <button
                    key={type}
                    type="button"
                    onClick={() => updateForm('orgType', type)}
                    className={`px-4 py-2 rounded-xl text-sm font-medium border transition-all
                      ${form.orgType === type
                        ? 'bg-[#0F172A] text-white border-[#0F172A]'
                        : 'bg-white text-gray-600 border-gray-200 hover:border-[#0F172A]/40'}`}
                  >
                    {type}
                  </button>
                ))}
              </div>
            </Field>

            <Field label="Chapter / Team Designation" hint="e.g. Alpha Beta, Varsity, etc.">
              <input
                type="text"
                value={form.designation}
                onChange={(e) => updateForm('designation', e.target.value)}
                placeholder="Optional"
                style={S.input(false)}
              />
            </Field>

            <Field label="Total Member Count *" hint="Active + alumni combined — approximate is fine" error={errors.memberCount}>
              <input
                type="number"
                min={1}
                value={form.memberCount}
                onChange={(e) => updateForm('memberCount', e.target.value)}
                placeholder="e.g. 250"
                style={S.input(!!errors.memberCount)}
              />
            </Field>

            {/* Live pricing display */}
            {price !== null && Number(form.memberCount) > 0 && (
              <div style={{ background: "#F9FAFB", border: "1px solid #0F172A", borderRadius: "12px", padding: "16px" }}>
                <div className="flex items-center gap-2 mb-1">
                  <DollarSign size={18} className="text-[#0F172A]" />
                  <span className="font-semibold text-[#0F172A]">Your plan: ${price}/month</span>
                </div>
                <p className="text-sm text-gray-500">Based on {form.memberCount} members · Annual commitment, then month-to-month</p>
              </div>
            )}

            <Field label="Leader Name *" hint="President / Captain / Director" error={errors.leaderName}>
              <input
                type="text"
                value={form.leaderName}
                onChange={(e) => updateForm('leaderName', e.target.value)}
                placeholder="Full name"
                style={S.input(!!errors.leaderName)}
              />
            </Field>

            <Field label="Leader Email *" error={errors.leaderEmail}>
              <input
                type="email"
                value={form.leaderEmail}
                onChange={(e) => updateForm('leaderEmail', e.target.value)}
                placeholder="you@email.com"
                style={S.input(!!errors.leaderEmail)}
              />
            </Field>

            <Field label="Leader Phone *" error={errors.leaderPhone}>
              <input
                type="tel"
                value={form.leaderPhone}
                onChange={(e) => updateForm('leaderPhone', e.target.value)}
                placeholder="+1 (555) 000-0000"
                style={S.input(!!errors.leaderPhone)}
              />
            </Field>

            <Field label="Instagram Handle" hint="Optional">
              <div className="flex items-center">
                <span className="px-3 py-2.5 bg-gray-100 text-gray-500 rounded-l-lg border border-gray-200 border-r-0 text-sm">@</span>
                <input
                  type="text"
                  value={form.instagramHandle}
                  onChange={(e) => updateForm('instagramHandle', e.target.value.replace('@', ''))}
                  placeholder="yourchapter"
                  className="flex-1 px-3 py-2.5 border border-gray-200 rounded-r-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#0F172A]/20 focus:border-[#0F172A]"
                />
              </div>
            </Field>
          </div>

          <div style={S.actions}>
            <button
              onClick={() => goToStep(0)}
              style={S.backBtn}
            >
              ← Back
            </button>
            <NavButton
              onClick={() => {
                if (validateStep1()) goToStep(2);
              }}
            >
              Continue <ChevronRight size={16} />
            </NavButton>
          </div>
        </Card>
      </PageShell>
    );
  }

  // ─── Step 2: Agreement ────────────────────────────────────────────────────

  if (step === 2) {
    const canProceed = agreedName.trim().length > 0 && agreedAuthorized;

    return (
      <PageShell testMode={testMode}>
        <StepIndicator current={2} />
        <Card>
          <h2 style={S.h2}>Here&apos;s what you&apos;re agreeing to</h2>
          <p style={S.sub}>Plain language, no surprises.</p>

          <div className="space-y-4 mb-8">
            {[
              {
                icon: <Zap size={20} className="text-[#0F172A]" />,
                title: "What you're getting",
                desc: "Access to the full Trailblaize platform for your organization — alumni directory, message board, engagement tools, and ongoing support.",
              },
              {
                icon: <Calendar size={20} className="text-[#0F172A]" />,
                title: 'Your commitment',
                desc: "This is a 12-month commitment starting today. After your first year, you can cancel anytime with 30 days notice. No hidden fees, no penalties.",
              },
              {
                icon: <DollarSign size={20} className="text-emerald-600" />,
                title: 'What it costs',
                desc: price
                  ? `$${price}/month · Billed monthly · Based on ${form.memberCount} members. Pricing may be updated at renewal with mutual agreement.`
                  : 'Pricing based on your member count.',
              },
              {
                icon: <Shield size={20} className="text-blue-500" />,
                title: 'Your data',
                desc: "Your data belongs to you. We use it only to run the platform. We never sell it. You can export or delete it anytime.",
              },
              {
                icon: <X size={20} className="text-gray-500" />,
                title: 'Cancellation',
                desc: "Cancel after year one with 30 days written notice. No penalty. Outstanding fees are still due at time of cancellation.",
              },
            ].map((card) => (
              <div key={card.title} className="bg-white border border-gray-200 rounded-2xl shadow-sm p-5 flex gap-4">
                <div className="mt-0.5 shrink-0">{card.icon}</div>
                <div>
                  <h3 className="font-semibold text-[#0F172A] mb-1">{card.title}</h3>
                  <p className="text-sm text-gray-500 leading-relaxed">{card.desc}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Full agreement toggle */}
          <button
            type="button"
            onClick={() => setShowFullAgreement((v) => !v)}
            className="flex items-center gap-2 text-sm text-[#0F172A] font-medium mb-3 hover:underline"
          >
            {showFullAgreement ? 'Hide full agreement ↑' : 'Read full agreement ↓'}
            <ChevronDown size={14} className={`transition-transform ${showFullAgreement ? 'rotate-180' : ''}`} />
          </button>

          {showFullAgreement && (
            <div className="bg-gray-50 border border-gray-200 rounded-xl p-4 mb-6 max-h-60 overflow-y-auto">
              <pre className="text-xs text-gray-500 whitespace-pre-wrap font-sans leading-relaxed">
                {FULL_AGREEMENT}
              </pre>
            </div>
          )}

          {/* Signature section */}
          <div className="bg-gray-50 border border-gray-200 rounded-2xl p-6 space-y-4">
            <p className="text-sm text-gray-600 font-medium">
              I agree to these terms on behalf of <span className="text-[#0F172A] font-semibold">{form.orgName || 'my organization'}</span>
            </p>

            <div>
              <label className="block text-xs font-medium text-gray-500 mb-1.5 uppercase tracking-wide">
                Type your full name to sign *
              </label>
              <input
                type="text"
                value={agreedName}
                onChange={(e) => setAgreedName(e.target.value)}
                placeholder="Your full name"
                className="w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#0F172A]/20 focus:border-[#0F172A]"
                style={{ fontFamily: 'cursive' }}
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-gray-500 mb-1.5 uppercase tracking-wide">Date</label>
              <p className="text-sm text-gray-700 bg-white border border-gray-200 rounded-lg px-3 py-2.5">{agreedAt}</p>
            </div>

            <label className="flex items-start gap-3 cursor-pointer">
              <div
                onClick={() => setAgreedAuthorized((v) => !v)}
                className={`w-5 h-5 rounded border-2 flex items-center justify-center shrink-0 mt-0.5 transition-all cursor-pointer
                  ${agreedAuthorized ? 'bg-[#0F172A] border-[#0F172A]' : 'border-gray-300 bg-white'}`}
              >
                {agreedAuthorized && <Check size={12} className="text-white" />}
              </div>
              <span className="text-sm text-gray-600 leading-relaxed">
                I confirm I am authorized to enter into this agreement on behalf of my organization
              </span>
            </label>
          </div>

          <div style={S.actions}>
            <button
              onClick={() => goToStep(1)}
              style={S.backBtn}
            >
              ← Back
            </button>
            <NavButton
              onClick={() => { if (canProceed) goToStep(3); }}
              disabled={!canProceed}
            >
              Continue to Payment <ChevronRight size={16} />
            </NavButton>
          </div>
        </Card>
      </PageShell>
    );
  }

  // ─── Step 3: Payment ──────────────────────────────────────────────────────

  if (step === 3) {
    return (
      <PageShell testMode={testMode}>
        <StepIndicator current={3} />
        <Card>
          <h2 style={S.h2}>Complete your payment</h2>
          <p style={S.sub}>You&apos;ll be redirected to Stripe&apos;s secure checkout.</p>

          {/* Summary */}
          <div className="bg-gray-50 border border-gray-200 rounded-2xl p-6 mb-6 space-y-3">
            <h3 className="font-semibold text-[#0F172A] mb-3">Order Summary</h3>
            <Row label="Organization" value={form.orgName} />
            <Row label="School" value={form.school} />
            <Row label="Type" value={form.orgType} />
            <Row label="Members" value={`${form.memberCount} members`} />
            <div className="border-t border-gray-200 pt-3 mt-3">
              <Row
                label="Monthly Price"
                value={price ? `$${price}/month` : '—'}
                valueClass="text-[#0F172A] font-bold text-lg"
              />
            </div>
            <p className="text-xs text-gray-400 pt-1">Annual commitment, then month-to-month · Cancel after year one with 30 days notice</p>
          </div>

          <div className="flex items-center gap-2 text-sm text-gray-500 mb-6">
            <Shield size={16} className="text-gray-400" />
            <span>Secured by Stripe — your payment info is never stored on our servers</span>
          </div>

          {checkoutError && (
            <div className="bg-red-50 text-red-700 rounded-xl px-4 py-3 text-sm mb-4">
              {checkoutError}
            </div>
          )}

          <div className="flex justify-between">
            <button
              onClick={() => goToStep(2)}
              style={S.backBtn}
            >
              ← Back
            </button>
            <NavButton onClick={handleCheckout} disabled={checkoutLoading}>
              {checkoutLoading ? (
                <><Loader2 size={16} className="animate-spin" /> Redirecting...</>
              ) : (
                <>Complete Payment <ArrowRight size={16} /></>
              )}
            </NavButton>
          </div>
        </Card>
      </PageShell>
    );
  }

  // ─── Step 4: Confirmation ─────────────────────────────────────────────────

  return (
    <PageShell testMode={testMode}>
      <StepIndicator current={4} />
      <Card>
        {confirmLoading ? (
          <div className="py-16 flex flex-col items-center gap-4 text-center">
            <Loader2 size={40} className="animate-spin text-[#0F172A]" />
            <p className="text-gray-500">Setting up your account…</p>
          </div>
        ) : confirmError ? (
          <div className="py-12 text-center">
            <p className="text-red-600 font-medium mb-2">Something went wrong</p>
            <p className="text-gray-500 text-sm mb-6">{confirmError}</p>
            <a href="mailto:support@trailblaize.net" className="text-[#0F172A] underline text-sm">
              Contact support
            </a>
          </div>
        ) : (
          <>
            {/* Big checkmark */}
            <div className="flex flex-col items-center text-center mb-8">
              <div className="w-20 h-20 rounded-full bg-emerald-100 flex items-center justify-center mb-4">
                <Check size={40} className="text-emerald-600" strokeWidth={3} />
              </div>
              <h2
                className="text-4xl font-bold text-[#0F172A]"
                style={{ fontFamily: 'Instrument Serif, Georgia, serif' }}
              >
                You&apos;re in.
              </h2>
              {(form.orgName || form.school) && (
                <p className="text-gray-500 mt-2 text-sm">
                  {form.orgName}{form.school ? ` · ${form.school}` : ''}
                </p>
              )}
            </div>

            {/* What happens next */}
            <div className="bg-gray-50 border border-gray-200 rounded-2xl p-6 mb-8">
              <h3 className="font-semibold text-[#0F172A] mb-4">What happens next</h3>
              <ul className="space-y-4">
                {[
                  { emoji: '✅', text: 'Your account is being created' },
                  { emoji: '📱', text: "We'll reach out within 24 hours to help you make your launch post" },
                  { emoji: '📅', text: 'Book your onboarding call to get set up for success' },
                  { emoji: '🔑', text: 'Log in to your new platform' },
                ].map((item) => (
                  <li key={item.text} className="flex items-start gap-3 text-sm text-gray-600">
                    <span className="text-base shrink-0">{item.emoji}</span>
                    <span>{item.text}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="flex flex-col sm:flex-row gap-3">
              <a
                href="https://calendly.com/trailblaize"
                target="_blank"
                rel="noopener noreferrer"
                className="flex-1 text-center px-6 py-3 border-2 border-[#0F172A] text-[#0F172A] rounded-xl font-semibold text-sm hover:bg-[#0F172A] hover:text-white transition-all"
              >
                Book Onboarding Call
              </a>
              <a
                href="https://trailblaize.space/login"
                className="flex-1 text-center px-6 py-3 bg-[#0F172A] text-white rounded-xl font-semibold text-sm hover:opacity-90 transition-all"
              >
                Log In →
              </a>
            </div>
          </>
        )}
      </Card>
    </PageShell>
  );
}

// ─── Helper Components ───────────────────────────────────────────────────────

function PageShell({ children, testMode }: { children: React.ReactNode; testMode?: boolean }) {
  return (
    <div style={{ background: '#F9FAFB', minHeight: '100vh' }}>
      {testMode && (
        <div style={{ background: '#fef3c7', borderBottom: '1px solid #f59e0b', padding: '8px 16px', textAlign: 'center', fontSize: '0.8125rem', fontWeight: 600, color: '#92400e' }}>
          🧪 TEST MODE — Use card 4242 4242 4242 4242 · No real charges will be made
        </div>
      )}
      <nav className="flex items-center px-4 sm:px-8 py-4 border-b border-gray-100" style={{ background: 'white' }}>
        <img src="/logos/logo-wordmark-navy.png" alt="Trailblaize" className="h-7" />
      </nav>
      <main className="max-w-2xl mx-auto px-4 sm:px-6 py-8 pb-16">
        {children}
      </main>
    </div>
  );
}

const S = {
  card: { background: 'white', border: '1px solid #E5E7EB', borderRadius: '16px', padding: '28px' },
  h2: { fontSize: '1.375rem', fontWeight: 700, color: '#111827', margin: '0 0 6px 0', fontFamily: 'Inter, system-ui, sans-serif' },
  sub: { fontSize: '0.875rem', color: '#6B7280', margin: '0 0 28px 0' },
  fieldWrap: { display: 'flex', flexDirection: 'column' as const, gap: '20px' },
  label: { display: 'block', fontSize: '0.8125rem', fontWeight: 600, color: '#374151', marginBottom: '6px', fontFamily: 'Inter, system-ui, sans-serif' },
  hint: { fontSize: '0.75rem', color: '#9ca3af', marginTop: '4px' },
  error: { fontSize: '0.75rem', color: '#ef4444', marginTop: '4px' },
  input: (hasError: boolean) => ({
    width: '100%', padding: '10px 12px', fontSize: '0.875rem',
    border: `1px solid ${hasError ? '#ef4444' : '#E5E7EB'}`,
    borderRadius: '10px', outline: 'none', fontFamily: 'Inter, system-ui, sans-serif',
    boxSizing: 'border-box' as const, color: '#111827', background: 'white',
  }),
  row: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '0.875rem' } as const,
  actions: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '28px' },
  backBtn: { fontSize: '0.875rem', color: '#9ca3af', background: 'none', border: 'none', cursor: 'pointer', fontFamily: 'Inter, system-ui, sans-serif', display: 'flex', alignItems: 'center', gap: '4px' },
  primaryBtn: (disabled?: boolean) => ({
    display: 'inline-flex', alignItems: 'center', gap: '6px',
    padding: '10px 24px', borderRadius: '10px',
    background: disabled ? '#D1D5DB' : '#0F172A',
    color: 'white', fontWeight: 600, fontSize: '0.875rem',
    border: 'none', cursor: disabled ? 'not-allowed' : 'pointer',
    fontFamily: 'Inter, system-ui, sans-serif',
  }),
};

function Card({ children }: { children: React.ReactNode }) {
  return <div style={S.card}>{children}</div>;
}

function Field({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: React.ReactNode }) {
  return (
    <div>
      <label style={S.label}>{label}</label>
      {children}
      {hint && !error && <p style={S.hint}>{hint}</p>}
      {error && <p style={S.error}>{error}</p>}
    </div>
  );
}

function Row({ label, value, valueClass }: { label: string; value: string; valueClass?: string }) {
  return (
    <div style={S.row}>
      <span style={{ color: '#6B7280' }}>{label}</span>
      <span style={valueClass === 'font-bold text-emerald-600' ? { fontWeight: 700, color: '#10b981' } : { fontWeight: 600, color: '#111827' }}>{value}</span>
    </div>
  );
}

function NavButton({ onClick, disabled, children }: { onClick: () => void; disabled?: boolean; children: React.ReactNode }) {
  return (
    <button type="button" onClick={onClick} disabled={disabled} style={S.primaryBtn(disabled)}>
      {children}
    </button>
  );
}

function inputCls(_hasError: boolean) {
  // Legacy — kept for any remaining uses; new code uses S.input()
  return '';
}

// Wrap in Suspense so useSearchParams() works with Next.js static export
export default function SetUpPageWrapper() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-[#F9FAFB] flex items-center justify-center"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#0F172A]" /></div>}>
      <SetUpPage />
    </Suspense>
  );
}
