import { OpenPrSummary } from '../github-repo';

const AUTO_GENERATED_MARKER = '<!-- auto-generated by Trailblaize Brain release_pr_watch -->';

/** True when the PR has no meaningful description worth preserving. */
export function isReleasePrBodyEmpty(body: string | null | undefined): boolean {
  if (!body) return true;
  const trimmed = body.trim();
  if (!trimmed) return true;
  if (trimmed === AUTO_GENERATED_MARKER) return true;
  if (trimmed.replace(AUTO_GENERATED_MARKER, '').trim() === '') return true;
  return false;
}

export function appendAutoGeneratedMarker(body: string): string {
  const trimmed = body.trimEnd();
  if (trimmed.includes(AUTO_GENERATED_MARKER)) return trimmed;
  return `${trimmed}\n\n${AUTO_GENERATED_MARKER}`;
}

export function releasePrLabel(pr: OpenPrSummary): string {
  return `develop → main #${pr.number}`;
}
