import { getSupabaseAdmin } from '@/lib/supabase-admin';
import {
  findReleasePullRequest,
  getGitHubRepoFull,
  getPullRequest,
  getPullRequestBody,
  isReleasePullRequest,
  listPullRequestCommits,
  updatePullRequestBody,
} from '../github-repo';
import { parseReleaseCommits, snapshotFromCommits } from './commits';
import { composeReleasePrDescription } from './compose';
import { appendAutoGeneratedMarker, isReleasePrBodyEmpty } from './detect';
import { postReleasePrToSlack } from './slack';
import { ReleasePrSnapshot, ReleasePrWatchResult, RunReleasePrWatchOptions } from './types';

async function wasPrAlreadyProcessed(prNumber: number): Promise<boolean> {
  const supabase = getSupabaseAdmin();
  if (!supabase) return false;

  const { data, error } = await supabase
    .from('brain_action_log')
    .select('id')
    .eq('skill_name', 'release_pr_watch')
    .eq('status', 'success')
    .filter('input->>pr_number', 'eq', String(prNumber))
    .limit(1);

  if (error) {
    console.warn('[brain/release-pr] dedupe check failed:', error.message);
    return false;
  }

  return (data?.length ?? 0) > 0;
}

async function logAutomationRun(
  prNumber: number,
  status: 'success' | 'failed',
  message: string,
  error?: string
): Promise<void> {
  const supabase = getSupabaseAdmin();
  if (!supabase) return;

  await supabase.from('brain_action_log').insert([
    {
      source: 'automation',
      skill_name: 'release_pr_watch',
      connector_name: 'github',
      input: { pr_number: prNumber, automation: 'release_pr_watch' },
      output: { message_preview: message.slice(0, 500) },
      status,
      error: error || null,
    },
  ]);

  const { error: autoError } = await supabase
    .from('brain_automations')
    .update({
      last_run_at: new Date().toISOString(),
      last_status: status,
      last_error: error || null,
      updated_at: new Date().toISOString(),
    })
    .eq('name', 'release_pr_watch');

  if (autoError) {
    console.warn('[brain/release-pr] brain_automations update skipped:', autoError.message);
  }
}

async function buildSnapshot(prNumber: number): Promise<ReleasePrSnapshot | null> {
  const repo = getGitHubRepoFull();
  const prData = await getPullRequest(prNumber, repo);
  const pr = {
    number: prData.number as number,
    title: String(prData.title ?? ''),
    url: String(prData.url ?? ''),
    author: (prData.author as string | undefined) ?? null,
    draft: false,
    created_at: typeof prData.created_at === 'string' ? prData.created_at : null,
    updated_at: typeof prData.updated_at === 'string' ? prData.updated_at : null,
    head: (prData.head as string | undefined) ?? null,
    base: (prData.base as string | undefined) ?? null,
  };

  if (!isReleasePullRequest(pr)) return null;

  const rawCommits = await listPullRequestCommits(prNumber, repo);
  const commits = parseReleaseCommits(rawCommits);
  const { ticketIds, includedPrNumbers } = snapshotFromCommits(commits);

  return {
    pr,
    repo,
    commits,
    ticketIds,
    includedPrNumbers,
    commitCount: rawCommits.length,
  };
}

/** Detect develop→main PR, compose description, update GitHub, notify Slack. */
export async function runReleasePrWatch(
  options: RunReleasePrWatchOptions = {}
): Promise<ReleasePrWatchResult> {
  const dryRun = options.dryRun ?? false;
  const shouldPost = options.postToSlack ?? !dryRun;
  const force = options.force ?? false;

  let prNumber = options.prNumber;
  if (!prNumber) {
    const releasePr = await findReleasePullRequest();
    if (!releasePr) {
      return { processed: false, skipped: true, reason: 'No open develop → main PR' };
    }
    prNumber = releasePr.number;
  }

  if (!force && (await wasPrAlreadyProcessed(prNumber))) {
    return {
      processed: false,
      skipped: true,
      reason: `PR #${prNumber} already processed`,
      prNumber,
    };
  }

  const existingBody = await getPullRequestBody(prNumber);
  if (!isReleasePrBodyEmpty(existingBody) && !force) {
    return {
      processed: false,
      skipped: true,
      reason: `PR #${prNumber} already has a description`,
      prNumber,
    };
  }

  const snapshot = await buildSnapshot(prNumber);
  if (!snapshot) {
    return {
      processed: false,
      skipped: true,
      reason: `PR #${prNumber} is not a develop → main release PR`,
      prNumber,
    };
  }

  const description = appendAutoGeneratedMarker(await composeReleasePrDescription(snapshot));

  if (!dryRun) {
    await updatePullRequestBody(prNumber, description, snapshot.repo);
  }

  let slack: ReleasePrWatchResult['slack'];
  if (shouldPost) {
    const posted = await postReleasePrToSlack(snapshot, description);
    slack = {
      attempted: posted.attempted,
      ok: posted.ok,
      targets: posted.targets,
      error: posted.error,
    };
  }

  const result: ReleasePrWatchResult = {
    processed: true,
    skipped: false,
    prNumber,
    prUrl: snapshot.pr.url,
    description,
    slack,
  };

  if (!dryRun) {
    try {
      await logAutomationRun(
        prNumber,
        slack?.attempted && !slack.ok ? 'failed' : 'success',
        description,
        slack?.error
      );
    } catch (err) {
      console.error('[brain/release-pr] audit log failed:', err);
    }
  }

  return result;
}
