export interface ScoutConversation {
  id: string;
  phone_number: string;
  linq_line: '+16462101111' | '+16462668785' | '+16462442696';
  linq_chat_id: string;
  direction: 'inbound' | 'outbound';
  message_body: string;
  read: boolean;
  flagged: boolean;
  flag_reason: string | null;
  created_at: string;
}

export interface ScoutProfile {
  id: string;
  phone_number: string;
  name: string;
  chapter: string;
  university: string;
  graduation_year: number;
  location: string;
  current_title: string;
  career_interest: string;
  goals: string[];
  skills: string[];
  looking_for: string;
  opt_in_status: 'opted_in' | 'opted_out' | 'pending';
  last_contact: string;
  next_followup: string | null;
  profile_complete: number;
  notes: string;
}

export interface ScoutIntroduction {
  id: string;
  requester: ScoutProfile;
  target: ScoutProfile;
  reason: string;
  status: 'suggested' | 'pending_approval' | 'sent' | 'accepted' | 'declined';
  created_at: string;
}

export const SCOUT_LINES = [
  { phone: '+16462101111' as const, label: 'Owen', color: '#3b82f6', daily_limit: 50 },
  { phone: '+16462668785' as const, label: 'Adam', color: '#10b981', daily_limit: 50 },
  { phone: '+16462442696' as const, label: 'Ford', color: '#8b5cf6', daily_limit: 50 },
] as const;

export function getLineLabel(phone: string): string {
  return SCOUT_LINES.find(l => l.phone === phone)?.label ?? phone;
}

export function getLineColor(phone: string): string {
  return SCOUT_LINES.find(l => l.phone === phone)?.color ?? '#6b7280';
}

// ─── Mock Profiles ────────────────────────────────────────────────────────────

export const MOCK_PROFILES: ScoutProfile[] = [
  {
    id: 'p1',
    phone_number: '+15551234001',
    name: 'Marcus Chen',
    chapter: 'Alpha Phi',
    university: 'USC',
    graduation_year: 2026,
    location: 'Los Angeles, CA',
    current_title: 'Product Management Intern',
    career_interest: 'Product Management',
    goals: ['Break into PM at a top-tier company', 'Build network in LA tech'],
    skills: ['Product strategy', 'SQL', 'User research', 'Figma'],
    looking_for: 'Mentors in PM, intro to hiring managers',
    opt_in_status: 'opted_in',
    last_contact: '2026-08-10T14:30:00Z',
    next_followup: '2026-08-14T10:00:00Z',
    profile_complete: 85,
    notes: 'Very engaged, responds quickly. Interested in connecting with Ford.',
  },
  {
    id: 'p2',
    phone_number: '+15551234002',
    name: 'Sophia Rodriguez',
    chapter: 'Kappa Delta',
    university: 'UT Austin',
    graduation_year: 2027,
    location: 'Austin, TX',
    current_title: 'Student',
    career_interest: 'Venture Capital',
    goals: ['Land VC internship', 'Learn deal sourcing'],
    skills: ['Financial modeling', 'Market research', 'Networking'],
    looking_for: 'Connections at VC firms, other aspiring VCs',
    opt_in_status: 'opted_in',
    last_contact: '2026-08-09T18:00:00Z',
    next_followup: '2026-08-13T10:00:00Z',
    profile_complete: 72,
    notes: 'Referred by Marcus. Eager to get involved.',
  },
  {
    id: 'p3',
    phone_number: '+15551234003',
    name: 'Jordan Williams',
    chapter: 'Sigma Chi',
    university: 'UVA',
    graduation_year: 2026,
    location: 'Charlottesville, VA',
    current_title: 'Software Engineer Intern',
    career_interest: 'Software Engineering',
    goals: ['Full-time SWE offer', 'Open source contributions'],
    skills: ['TypeScript', 'React', 'Python', 'System design'],
    looking_for: 'Engineering mentors, study partners for system design',
    opt_in_status: 'opted_in',
    last_contact: '2026-08-11T09:15:00Z',
    next_followup: null,
    profile_complete: 90,
    notes: 'Strong technical background. Could be good match for Devin.',
  },
  {
    id: 'p4',
    phone_number: '+15551234004',
    name: 'Emma Thompson',
    chapter: 'Chi Omega',
    university: 'Michigan',
    graduation_year: 2027,
    location: 'Ann Arbor, MI',
    current_title: 'Student',
    career_interest: 'Consulting',
    goals: ['MBB internship', 'Case prep partners'],
    skills: ['Case interviews', 'Data analysis', 'Presentations'],
    looking_for: 'Case prep partners, consulting mentors',
    opt_in_status: 'pending',
    last_contact: '2026-08-08T12:00:00Z',
    next_followup: '2026-08-12T10:00:00Z',
    profile_complete: 45,
    notes: 'New contact. Needs follow-up to complete profile.',
  },
  {
    id: 'p5',
    phone_number: '+15551234005',
    name: 'Tyler Jackson',
    chapter: 'Delta Tau Delta',
    university: 'Georgia Tech',
    graduation_year: 2026,
    location: 'Atlanta, GA',
    current_title: 'Data Science Intern',
    career_interest: 'Data Science / ML',
    goals: ['ML engineer role', 'Publish research paper'],
    skills: ['Python', 'TensorFlow', 'Statistics', 'SQL'],
    looking_for: 'ML engineers at FAANG, research collaborators',
    opt_in_status: 'opted_in',
    last_contact: '2026-08-10T20:00:00Z',
    next_followup: '2026-08-15T10:00:00Z',
    profile_complete: 78,
    notes: '',
  },
  {
    id: 'p6',
    phone_number: '+15551234006',
    name: 'Ava Martinez',
    chapter: 'Alpha Chi Omega',
    university: 'NYU',
    graduation_year: 2027,
    location: 'New York, NY',
    current_title: 'Marketing Intern',
    career_interest: 'Brand Marketing',
    goals: ['Brand manager role', 'Build portfolio'],
    skills: ['Social media', 'Copywriting', 'Adobe Creative Suite'],
    looking_for: 'Marketing professionals, creative collaborators',
    opt_in_status: 'opted_in',
    last_contact: '2026-08-07T16:30:00Z',
    next_followup: '2026-08-12T10:00:00Z',
    profile_complete: 60,
    notes: 'Interested in our ambassador program too.',
  },
  {
    id: 'p7',
    phone_number: '+15551234007',
    name: 'Ryan Park',
    chapter: 'Beta Theta Pi',
    university: 'Stanford',
    graduation_year: 2026,
    location: 'Palo Alto, CA',
    current_title: 'Startup Founder',
    career_interest: 'Entrepreneurship',
    goals: ['Raise seed round', 'Find technical cofounder'],
    skills: ['Fundraising', 'Sales', 'Product vision', 'Hiring'],
    looking_for: 'VCs, technical cofounders, other founders',
    opt_in_status: 'opted_out',
    last_contact: '2026-07-28T10:00:00Z',
    next_followup: null,
    profile_complete: 95,
    notes: 'Opted out after feeling spammed. Handle with care if re-engaging.',
  },
  {
    id: 'p8',
    phone_number: '+15551234008',
    name: 'Isabella Nguyen',
    chapter: 'Gamma Phi Beta',
    university: 'UCLA',
    graduation_year: 2027,
    location: 'Los Angeles, CA',
    current_title: 'Student',
    career_interest: 'Investment Banking',
    goals: ['IB summer analyst', 'Technical skills development'],
    skills: ['Excel', 'Financial modeling', 'Valuation'],
    looking_for: 'IB analysts for coffee chats, networking events',
    opt_in_status: 'pending',
    last_contact: '2026-08-11T11:00:00Z',
    next_followup: '2026-08-13T10:00:00Z',
    profile_complete: 30,
    notes: 'Just started conversation. Very early stage.',
  },
  {
    id: 'p9',
    phone_number: '+15551234009',
    name: 'Daniel Kim',
    chapter: 'Phi Delta Theta',
    university: 'Duke',
    graduation_year: 2026,
    location: 'Durham, NC',
    current_title: 'Strategy Intern',
    career_interest: 'Corporate Strategy',
    goals: ['Strategy role post-grad', 'MBA preparation'],
    skills: ['Strategy frameworks', 'Market sizing', 'Competitive analysis'],
    looking_for: 'Strategy professionals, MBA mentors',
    opt_in_status: 'opted_in',
    last_contact: '2026-08-09T14:00:00Z',
    next_followup: '2026-08-14T10:00:00Z',
    profile_complete: 68,
    notes: 'Good candidate for intro to Marcus — both interested in strategy/PM.',
  },
];

// ─── Mock Conversations ───────────────────────────────────────────────────────

export const MOCK_CONVERSATIONS: ScoutConversation[] = [
  // Thread 1: Marcus Chen (+15551234001) via Owen's line
  {
    id: 'c1',
    phone_number: '+15551234001',
    linq_line: '+16462101111',
    linq_chat_id: 'chat_001',
    direction: 'outbound',
    message_body: 'Hey Marcus! This is Scout from Trailblaize. We connect ambitious students with mentors and opportunities in their target industry. Mind if I ask a few questions about what you\'re looking for?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-09T10:00:00Z',
  },
  {
    id: 'c2',
    phone_number: '+15551234001',
    linq_line: '+16462101111',
    linq_chat_id: 'chat_001',
    direction: 'inbound',
    message_body: 'Hey! Yeah for sure, I\'ve been looking for something like this. I\'m trying to break into PM — what do you need to know?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-09T10:15:00Z',
  },
  {
    id: 'c3',
    phone_number: '+15551234001',
    linq_line: '+16462101111',
    linq_chat_id: 'chat_001',
    direction: 'outbound',
    message_body: 'Awesome! What school/chapter are you in, and what year do you graduate? Also what specific PM areas interest you most — B2B, consumer, growth?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-09T10:20:00Z',
  },
  {
    id: 'c4',
    phone_number: '+15551234001',
    linq_line: '+16462101111',
    linq_chat_id: 'chat_001',
    direction: 'inbound',
    message_body: 'USC, Alpha Phi, graduating 2026. I\'m most interested in consumer PM — think Instagram, Spotify, that kind of thing. Currently interning at a startup doing product work.',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-09T11:00:00Z',
  },
  {
    id: 'c5',
    phone_number: '+15551234001',
    linq_line: '+16462101111',
    linq_chat_id: 'chat_001',
    direction: 'outbound',
    message_body: 'Perfect — we have a few people in our network at consumer companies. I\'ll flag some potential intros for you. Quick q: are you open to connecting with other aspiring PMs for mutual support too?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-10T14:30:00Z',
  },
  {
    id: 'c6',
    phone_number: '+15551234001',
    linq_line: '+16462101111',
    linq_chat_id: 'chat_001',
    direction: 'inbound',
    message_body: 'Absolutely, that would be great. The more the merrier 🙌',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-10T14:45:00Z',
  },

  // Thread 2: Sophia Rodriguez (+15551234002) via Adam's line
  {
    id: 'c7',
    phone_number: '+15551234002',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_002',
    direction: 'outbound',
    message_body: 'Hi Sophia! Marcus mentioned you might be interested in our networking community. We help students break into VC, consulting, tech — is that something you\'d be into?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-08T14:00:00Z',
  },
  {
    id: 'c8',
    phone_number: '+15551234002',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_002',
    direction: 'inbound',
    message_body: 'Yes! Marcus told me about you guys. I\'m really interested in VC — trying to land an internship next summer. How does it work?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-08T15:30:00Z',
  },
  {
    id: 'c9',
    phone_number: '+15551234002',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_002',
    direction: 'outbound',
    message_body: 'Great! We match you with people who can help — whether that\'s current VCs, other students going through recruiting, or founders who\'ve raised. A few quick questions: what year/school, and have you done any VC-related work yet?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-09T09:00:00Z',
  },
  {
    id: 'c10',
    phone_number: '+15551234002',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_002',
    direction: 'inbound',
    message_body: 'UT Austin, Kappa Delta, rising junior. I run our chapter\'s investment fund (small but real money lol) and have done market research for a local seed fund.',
    read: false,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-09T18:00:00Z',
  },

  // Thread 3: Jordan Williams (+15551234003) via Ford's line
  {
    id: 'c11',
    phone_number: '+15551234003',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_003',
    direction: 'outbound',
    message_body: 'Hey Jordan! We\'re building a community of ambitious students in tech. Heard you\'re a strong engineer — would you be open to chatting about what you\'re looking for career-wise?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-10T08:00:00Z',
  },
  {
    id: 'c12',
    phone_number: '+15551234003',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_003',
    direction: 'inbound',
    message_body: 'Sure! I\'m at UVA studying CS, graduating next May. Looking for full-time SWE roles — ideally at a company doing interesting infra work. Also contributing to open source.',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-10T09:30:00Z',
  },
  {
    id: 'c13',
    phone_number: '+15551234003',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_003',
    direction: 'outbound',
    message_body: 'That\'s awesome. We have a few engineers in our network at places like Vercel, Cloudflare, Linear. Would intros to any of those be helpful?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-11T09:00:00Z',
  },
  {
    id: 'c14',
    phone_number: '+15551234003',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_003',
    direction: 'inbound',
    message_body: 'Vercel and Linear would be incredible. I\'m actually building a project with Next.js right now. When could that happen?',
    read: false,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-11T09:15:00Z',
  },

  // Thread 4: Emma Thompson (+15551234004) via Owen's line — incomplete profile
  {
    id: 'c15',
    phone_number: '+15551234004',
    linq_line: '+16462101111',
    linq_chat_id: 'chat_004',
    direction: 'outbound',
    message_body: 'Hi Emma! I\'m reaching out from Trailblaize — we connect students with mentors and peers in their target careers. What industry are you most interested in?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-07T10:00:00Z',
  },
  {
    id: 'c16',
    phone_number: '+15551234004',
    linq_line: '+16462101111',
    linq_chat_id: 'chat_004',
    direction: 'inbound',
    message_body: 'Consulting! Specifically MBB. Is this a paid thing?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-08T12:00:00Z',
  },

  // Thread 5: Tyler Jackson (+15551234005) via Adam's line
  {
    id: 'c17',
    phone_number: '+15551234005',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_005',
    direction: 'outbound',
    message_body: 'Hey Tyler! We\'re connecting students in data science and ML with industry professionals. Saw you\'re at Georgia Tech doing DS — want to hear more?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-09T14:00:00Z',
  },
  {
    id: 'c18',
    phone_number: '+15551234005',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_005',
    direction: 'inbound',
    message_body: 'Yeah definitely. I\'m trying to move into ML engineering specifically — not just analytics. Any connections in that space?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-09T16:00:00Z',
  },
  {
    id: 'c19',
    phone_number: '+15551234005',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_005',
    direction: 'outbound',
    message_body: 'Absolutely. We know folks at a few ML-heavy companies. Tell me more about your background — what frameworks are you working with, and any published work?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'c20',
    phone_number: '+15551234005',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_005',
    direction: 'inbound',
    message_body: 'TensorFlow and PyTorch mainly. Working on a paper about efficient fine-tuning for my advisor. Should be submitted by October.',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-10T20:00:00Z',
  },

  // Thread 6: Ryan Park (+15551234007) via Ford's line — FLAGGED (opted out)
  {
    id: 'c21',
    phone_number: '+15551234007',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_007',
    direction: 'outbound',
    message_body: 'Hey Ryan! We\'re connecting founders with VCs and potential cofounders. Interested in hearing more?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-07-25T10:00:00Z',
  },
  {
    id: 'c22',
    phone_number: '+15551234007',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_007',
    direction: 'inbound',
    message_body: 'Sure, what is this exactly?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-07-25T14:00:00Z',
  },
  {
    id: 'c23',
    phone_number: '+15551234007',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_007',
    direction: 'outbound',
    message_body: 'We match ambitious students and young professionals with mentors and opportunities. Since you\'re a founder, we could connect you with VCs in our network or technical cofounders.',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-07-26T09:00:00Z',
  },
  {
    id: 'c24',
    phone_number: '+15551234007',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_007',
    direction: 'outbound',
    message_body: 'Following up — would any of those be helpful for you right now?',
    read: true,
    flagged: true,
    flag_reason: 'User asked to stop receiving messages after second follow-up',
    created_at: '2026-07-27T10:00:00Z',
  },
  {
    id: 'c25',
    phone_number: '+15551234007',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_007',
    direction: 'inbound',
    message_body: 'Hey please stop texting me. I get too many of these. Remove me from your list.',
    read: true,
    flagged: true,
    flag_reason: 'User asked to stop receiving messages after second follow-up',
    created_at: '2026-07-28T10:00:00Z',
  },

  // Thread 7: Isabella Nguyen (+15551234008) via Owen's line — new/pending
  {
    id: 'c26',
    phone_number: '+15551234008',
    linq_line: '+16462101111',
    linq_chat_id: 'chat_008',
    direction: 'outbound',
    message_body: 'Hi Isabella! This is Scout from Trailblaize — we help students break into competitive industries through warm intros. Are you recruiting for anything right now?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-11T10:00:00Z',
  },
  {
    id: 'c27',
    phone_number: '+15551234008',
    linq_line: '+16462101111',
    linq_chat_id: 'chat_008',
    direction: 'inbound',
    message_body: 'Hi! Yes actually — I\'m trying to get into investment banking. Summer analyst recruiting starts soon and I feel super behind.',
    read: false,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-11T11:00:00Z',
  },

  // Thread 8: Daniel Kim (+15551234009) via Adam's line
  {
    id: 'c28',
    phone_number: '+15551234009',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_009',
    direction: 'outbound',
    message_body: 'Hey Daniel! We connect students with professionals in strategy, consulting, and tech. Heard you might be a good fit — interested?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-08T10:00:00Z',
  },
  {
    id: 'c29',
    phone_number: '+15551234009',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_009',
    direction: 'inbound',
    message_body: 'Yeah! I\'m doing corporate strategy at a Fortune 500 this summer and thinking about what\'s next. Definitely open to connecting.',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-08T14:30:00Z',
  },
  {
    id: 'c30',
    phone_number: '+15551234009',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_009',
    direction: 'outbound',
    message_body: 'Nice! Where are you based and what does your ideal next step look like? Full-time strategy or thinking about pivoting to something else?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-09T09:00:00Z',
  },
  {
    id: 'c31',
    phone_number: '+15551234009',
    linq_line: '+16462668785',
    linq_chat_id: 'chat_009',
    direction: 'inbound',
    message_body: 'Duke, Phi Delt. Ideally want to stay in strategy but open to product roles too. Also thinking about MBA in a few years so any advice there would be huge.',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-09T14:00:00Z',
  },

  // Thread 9: Ava Martinez (+15551234006) via Ford's line — FLAGGED (inappropriate)
  {
    id: 'c32',
    phone_number: '+15551234006',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_006',
    direction: 'outbound',
    message_body: 'Hi Ava! We\'re building a community of ambitious students in marketing, tech, and finance. Interested in connecting with professionals in brand marketing?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-06T10:00:00Z',
  },
  {
    id: 'c33',
    phone_number: '+15551234006',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_006',
    direction: 'inbound',
    message_body: 'Sure, sounds cool! What kind of marketing professionals are in your network?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-06T12:00:00Z',
  },
  {
    id: 'c34',
    phone_number: '+15551234006',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_006',
    direction: 'outbound',
    message_body: 'We have brand managers at Nike, L\'Oreal, and a couple of DTC founders. Also some social media leads at agencies. Want me to look for specific matches?',
    read: true,
    flagged: false,
    flag_reason: null,
    created_at: '2026-08-07T09:00:00Z',
  },
  {
    id: 'c35',
    phone_number: '+15551234006',
    linq_line: '+16462442696',
    linq_chat_id: 'chat_006',
    direction: 'inbound',
    message_body: 'OMG Nike would be amazing!! Also are you guys hiring? I saw you have an ambassador program. Would love to be involved on your end too',
    read: true,
    flagged: true,
    flag_reason: 'User expressed interest in working for Trailblaize — route to ambassador team',
    created_at: '2026-08-07T16:30:00Z',
  },
];

// ─── Mock Introductions ───────────────────────────────────────────────────────

export const MOCK_INTRODUCTIONS: ScoutIntroduction[] = [
  {
    id: 'i1',
    requester: MOCK_PROFILES[0], // Marcus Chen
    target: MOCK_PROFILES[8],    // Daniel Kim
    reason: 'Both interested in product/strategy roles. Marcus is in PM, Daniel in corporate strategy — could swap tips on breaking in.',
    status: 'suggested',
    created_at: '2026-08-10T16:00:00Z',
  },
  {
    id: 'i2',
    requester: MOCK_PROFILES[1], // Sophia Rodriguez
    target: MOCK_PROFILES[6],    // Ryan Park (founder)
    reason: 'Sophia wants to learn deal sourcing for VC; Ryan is actively raising — she could practice analyzing his startup.',
    status: 'pending_approval',
    created_at: '2026-08-09T12:00:00Z',
  },
  {
    id: 'i3',
    requester: MOCK_PROFILES[2], // Jordan Williams
    target: MOCK_PROFILES[4],    // Tyler Jackson
    reason: 'Both strong technical builders. Jordan does frontend/infra, Tyler does ML — could collaborate on an open source project.',
    status: 'sent',
    created_at: '2026-08-05T10:00:00Z',
  },
  {
    id: 'i4',
    requester: MOCK_PROFILES[3], // Emma Thompson
    target: MOCK_PROFILES[8],    // Daniel Kim
    reason: 'Both targeting consulting/strategy. Could be case prep partners.',
    status: 'declined',
    created_at: '2026-08-03T10:00:00Z',
  },
];
